//! Demo 01 — the Golden Triangle (§6 M2), scene half. The lib target is the
//! *scene*: the generated shader artifacts and the values a frame needs.
//! gg-golden renders exactly this — same SPIR-V, same push constants — so the
//! golden test guards the demo, not a lookalike. No windowing anywhere in
//! this half; the app rides behind the `app` feature (§5 gate 7).

/// Generated by `cargo xtask shaders` from `shaders/triangle.slang` (§4.4).
pub mod shaders_gen {
    /// The triangle module: push-constant struct + embedded SPIR-V.
    pub mod triangle;
}

use gg_render::graph::{Declared, Load, ResourceId, single_pass};
use gg_rhi::DrawSpec;
use shaders_gen::triangle as shader;

/// Background clear color (linear values; the sRGB target encodes).
pub const CLEAR: [f32; 4] = [0.015, 0.015, 0.025, 1.0];

/// One triangle.
pub const VERTEX_COUNT: u32 = 3;

/// The extent gg-golden captures at (§4.10 v0: fixed-size offscreen target).
pub const GOLDEN_EXTENT: (u32, u32) = (640, 360);

/// The scene's pipeline, straight from the embedded offline build.
pub fn pipeline_desc() -> gg_rhi::PipelineDesc<'static> {
    gg_rhi::PipelineDesc {
        name: "triangle",
        vs_spirv: shader::VS_MAIN_SPIRV,
        vs_entry: shader::VS_MAIN_ENTRY,
        fs_spirv: shader::FS_MAIN_SPIRV,
        fs_entry: shader::FS_MAIN_ENTRY,
        push_constant_size: core::mem::size_of::<shader::TrianglePush>() as u32,
        color: gg_rhi::ColorTarget::Backbuffer,
        // One triangle, nothing behind it: this pass declares no depth
        // attachment at all, which under dynamic rendering is what a pipeline
        // that ignores depth has to say.
        blend: gg_rhi::Blend::Off,
        depth: gg_rhi::DepthMode::Off,
        depth_bias: false,
    }
}

/// The scene's graph: one pass into the backbuffer (§4.5). Shared by the app
/// and by gg-golden, so the golden guards the demo's *frame* and not just its
/// draw call.
pub fn declare<'a>(backbuffer: ResourceId, draws: &'a [DrawSpec<'a>]) -> [Declared<'a>; 1] {
    single_pass("triangle", backbuffer, Load::Clear(CLEAR), draws)
}

/// Push constants for a frame at `extent`: aspect-corrected transform (the
/// triangle stays a triangle at any window shape), white tint.
pub fn push_for_extent(extent: (u32, u32)) -> shader::TrianglePush {
    let (w, h) = (extent.0.max(1) as f32, extent.1.max(1) as f32);
    // Fit the [-1,1] scene into the wider axis: undistorted at 16:9 and 9:16 alike.
    let (sx, sy) = if w >= h { (h / w, 1.0) } else { (1.0, w / h) };
    shader::TrianglePush::new(
        [
            [sx, 0.0, 0.0, 0.0],
            [0.0, sy, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
        ],
        [1.0, 1.0, 1.0, 1.0],
    )
}
