//! Demo 02 — Real Geometry (M4A), then Real Sim (M4B).
//!
//! The crate is in two halves either side of the §1.4 membrane, and the split
//! is a *feature* split rather than a module convention because the halves have
//! different dependency graphs:
//!
//! - [`sim`] and [`gate`] — ECS-resident simulation state advanced from action
//!   maps, and the replay determinism gate over it (§5.6). `gg-ecs`,
//!   `gg-input` and `gg_math::sim` and nothing else, so the determinism gate and
//!   the aarch64-under-qemu leg build and run it with no GPU, no windowing and
//!   no `ash` anywhere in the graph (§5.6).
//! - [`scene`](crate) behind the `scene` feature — the mesh, the BC7 texture,
//!   the upload path and the render-side camera. gg-golden takes this without
//!   `app`, so its graph never touches winit (§5 gate 7).
//!
//! What M4A proved lives in the second half in miniature: geometry pulled
//! through a buffer device address, a block-compressed texture that crossed the
//! transfer queue, one bindless index standing in for a material, and reverse-Z
//! sorting the faces of a cube deliberately spinning through itself. What M4B
//! adds is that none of it is driven by a variable the sim does not own.

pub mod bc7;
pub mod sim;

/// The determinism gate's material (§5.6). Behind `gate` because it is test and
/// authoring material: `xtask replay --bless` and `tests/determinism.rs` want
/// it, a shipped binary does not.
#[cfg(feature = "gate")]
pub mod gate;

/// Generated by `cargo xtask shaders` from `shaders/mesh.slang` (§4.4).
#[cfg(feature = "scene")]
pub mod shaders_gen {
    /// The mesh module: push-constant struct + embedded SPIR-V.
    pub mod mesh;
}

#[cfg(feature = "scene")]
mod scene;

// Re-exported flat: the scene half was the whole crate through M4A, and every
// caller (gg-golden, the app) names `demo_02_mesh::upload`. Moving it into a
// module for the feature split should not move it for them.
#[cfg(feature = "scene")]
pub use scene::*;
