// @generated by `cargo xtask shaders` from shaders/mesh.slang — do not edit.
// source-hash: sha256:418e7e61c941d15e6519a7cda23847c65cba7d8f86a5b97d067f1e8e23c35a29 generator: v4
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `MeshPush` — std430 layout, 80 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct MeshPush {
    /// offset 0
    pub view_projection: [[f32; 4]; 4],
    /// offset 64
    pub vertices: u64,
    /// offset 72
    pub texture_index: u32,
    /// offset 76
    pub sampler_index: u32,
}

impl MeshPush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        view_projection: [[f32; 4]; 4],
        vertices: u64,
        texture_index: u32,
        sampler_index: u32,
    ) -> Self {
        Self {
            view_projection,
            vertices,
            texture_index,
            sampler_index,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<MeshPush>() == 80);
    assert!(core::mem::offset_of!(MeshPush, view_projection) == 0);
    assert!(core::mem::offset_of!(MeshPush, vertices) == 64);
    assert!(core::mem::offset_of!(MeshPush, texture_index) == 72);
    assert!(core::mem::offset_of!(MeshPush, sampler_index) == 76);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("mesh.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("mesh.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
