//! Reflection → Rust codegen (§4.4). The reflected push-constant layout
//! becomes a `repr(C)` + `bytemuck::Pod` struct whose size and every field
//! offset are frozen as compile-time assertions — a shader/CPU struct mismatch
//! is a **build error**, not a Saturday of debugging std430 offsets. Where
//! std430 and `repr(C)` disagree by gaps, explicit padding fields are
//! generated; where they disagree by shape (stride mismatches), compilation
//! already failed loudly in reflection.
//!
//! Output is a pure function of the reflected facts plus the source hash, so
//! the checked-in files are diffable and CI's diff-clean gate (§5, gate 3) can
//! hold them against the sources.

use crate::{CompiledModule, ShaderError, Stage};

/// Bumped whenever generated output changes shape; part of the header line the
/// incremental/diff-clean machinery compares.
pub const GENERATOR_VERSION: u32 = 4;

/// The header line carrying the identity of the inputs. `xtask shaders` skips
/// recompilation when the on-disk header matches the current source hash.
pub fn header_line(source_hash_hex: &str) -> String {
    format!("// source-hash: sha256:{source_hash_hex} generator: v{GENERATOR_VERSION}")
}

/// Generate the Rust module for `module_stem` (e.g. `triangle` for
/// `triangle.slang`). The text `include_bytes!`s the sibling
/// `<stem>.<entry>.spv` files the caller writes alongside.
pub fn generate(
    module_stem: &str,
    module: &CompiledModule,
    source_hash_hex: &str,
) -> Result<String, ShaderError> {
    let mut out = String::new();
    out.push_str(&format!(
        "// @generated by `cargo xtask shaders` from shaders/{module_stem}.slang — do not edit.\n"
    ));
    out.push_str(&header_line(source_hash_hex));
    out.push_str(
        "\n//\n// Layout facts reflected from Slang, frozen as compile-time assertions:\n",
    );
    out.push_str("// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).\n\n");

    if let Some(push) = &module.push_constants {
        generate_struct(&mut out, push)?;
    }

    for ep in &module.entry_points {
        let stage = match ep.stage {
            Stage::Vertex => "vertex",
            Stage::Fragment => "fragment",
            Stage::Compute => "compute",
        };
        let ident = sanitize_upper(&ep.name);
        out.push_str(&format!(
            "/// SPIR-V for entry point `{}` ({stage}).\n\
             pub static {ident}_SPIRV: &[u8] = include_bytes!(\"{module_stem}.{}.spv\");\n\
             /// The `OpEntryPoint` name inside [`{ident}_SPIRV`].\n\
             pub const {ident}_ENTRY: &str = \"{}\";\n\n",
            ep.name, ep.name, ep.spirv_entry
        ));
    }
    // rustfmt-stable output: exactly one trailing newline, so `cargo fmt`
    // never disagrees with the diff-clean gate about generated bytes.
    while out.ends_with("\n\n") {
        out.pop();
    }
    Ok(out)
}

fn generate_struct(out: &mut String, push: &crate::StructLayout) -> Result<(), ShaderError> {
    let name = sanitize_ident(&push.name);
    let mut asserts = vec![format!(
        "    assert!(core::mem::size_of::<{name}>() == {});",
        push.size
    )];
    let mut body = String::new();
    let mut ctor_params = Vec::new();
    let mut ctor_fields = Vec::new();
    let mut cursor = 0usize; // current repr(C) end offset
    let mut pad_index = 0u32;

    for field in &push.fields {
        if field.offset < cursor {
            return Err(ShaderError::Unsupported(format!(
                "field `{}` overlaps the previous field (offset {} < {})",
                field.name, field.offset, cursor
            )));
        }
        if field.offset > cursor {
            let pad = field.offset - cursor;
            body.push_str(&format!(
                "    /// std430 padding — carries no data.\n    pub _pad{pad_index}: [u8; {pad}],\n"
            ));
            ctor_fields.push(format!("_pad{pad_index}: [0; {pad}]"));
            pad_index += 1;
        }
        let fname = sanitize_ident(&field.name);
        let rust_ty = field.ty.rust_type();
        body.push_str(&format!(
            "    /// offset {}\n    pub {fname}: {rust_ty},\n",
            field.offset
        ));
        asserts.push(format!(
            "    assert!(core::mem::offset_of!({name}, {fname}) == {});",
            field.offset
        ));
        ctor_params.push(format!("{fname}: {rust_ty}"));
        ctor_fields.push(fname);
        cursor = field.offset + field.size;
    }
    if push.size > cursor {
        let pad = push.size - cursor;
        body.push_str(&format!(
            "    /// std430 tail padding — carries no data.\n    pub _pad{pad_index}: [u8; {pad}],\n"
        ));
        ctor_fields.push(format!("_pad{pad_index}: [0; {pad}]"));
    }

    out.push_str(&format!(
        "/// Push-constant block `{}` — std430 layout, {} bytes.\n\
         #[repr(C)]\n\
         #[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]\n\
         pub struct {name} {{\n{body}}}\n\n",
        push.name, push.size
    ));
    out.push_str(&format!(
        "impl {name} {{\n    /// Construct with every padding byte zeroed.\n    pub fn new({}) -> Self {{\n        Self {{{}}}\n    }}\n}}\n\n",
        wrap_list(&ctor_params, "    pub fn new(".len() + ") -> Self {".len(), 8),
        wrap_braced(&ctor_fields, 12),
    ));
    out.push_str(&format!(
        "const _: () = {{\n{}\n}};\n\n",
        asserts.join("\n")
    ));
    Ok(())
}

/// rustfmt's max width. Generated output has to be a *fixed point* of `cargo
/// fmt`, or the formatter and the diff-clean gate (§5, gate 3) disagree about
/// the checked-in bytes forever — so the two places a generated line can grow
/// past it reproduce rustfmt's own rule rather than hoping to stay short.
const MAX_WIDTH: usize = 100;

/// A comma-separated parameter list: joined on one line while it fits, else
/// one item per line at `indent`, with a trailing comma — what rustfmt does.
/// `fixed` is everything else on the line the joined form would occupy.
fn wrap_list(items: &[String], fixed: usize, indent: usize) -> String {
    let joined = items.join(", ");
    if items.is_empty() || fixed + joined.len() <= MAX_WIDTH {
        return joined;
    }
    let pad = " ".repeat(indent);
    let mut out = String::from("\n");
    for item in items {
        out.push_str(&format!("{pad}{item},\n"));
    }
    out.push_str(&" ".repeat(indent - 4));
    out
}

/// As [`wrap_list`], for a struct literal's fields — which rustfmt writes with
/// surrounding spaces on one line (`{ a, b }`) and without them when split.
///
/// The threshold is *not* `max_width`: rustfmt's `struct_lit_width` defaults to
/// 18 and measures the contents alone, so a short literal on a long line stays
/// joined and a 54-character one splits at column 8.
fn wrap_braced(items: &[String], indent: usize) -> String {
    const STRUCT_LIT_WIDTH: usize = 18;
    let joined = items.join(", ");
    if items.is_empty() {
        return String::new();
    }
    if joined.len() <= STRUCT_LIT_WIDTH {
        return format!(" {joined} ");
    }
    let pad = " ".repeat(indent);
    let mut out = String::from("\n");
    for item in items {
        out.push_str(&format!("{pad}{item},\n"));
    }
    out.push_str(&" ".repeat(indent - 4));
    out
}

/// Field/struct names pass through as-is when already valid Rust identifiers;
/// anything else maps to `_`. Shader authors see their own names in Rust.
fn sanitize_ident(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

fn sanitize_upper(name: &str) -> String {
    sanitize_ident(name).to_ascii_uppercase()
}
