// @generated by `cargo xtask shaders` from shaders/ao.slang — do not edit.
// source-hash: sha256:92761c6d5d09d6b41cca392fa50f49cc86ee008533d30cc2ab80bd60d933e4cb generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `AoPush` — std430 layout, 72 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct AoPush {
    /// offset 0
    pub depth_index: u32,
    /// offset 4
    pub source_index: u32,
    /// offset 8
    pub sampler_index: u32,
    /// offset 12
    pub projection: u32,
    /// offset 16
    pub texel: [f32; 2],
    /// offset 24
    pub extent: [f32; 2],
    /// offset 32
    pub project: [f32; 2],
    /// offset 40
    pub depth_params: [f32; 2],
    /// offset 48
    pub radius: f32,
    /// offset 52
    pub intensity: f32,
    /// offset 56
    pub slices: u32,
    /// offset 60
    pub steps: u32,
    /// offset 64
    pub falloff: f32,
    /// offset 68
    pub min_pixels: f32,
}

impl AoPush {
    /// Construct with every padding byte zeroed.
    #[expect(
        clippy::too_many_arguments,
        reason = "one field per push-constant member; the shader decides how many"
    )]
    pub fn new(
        depth_index: u32,
        source_index: u32,
        sampler_index: u32,
        projection: u32,
        texel: [f32; 2],
        extent: [f32; 2],
        project: [f32; 2],
        depth_params: [f32; 2],
        radius: f32,
        intensity: f32,
        slices: u32,
        steps: u32,
        falloff: f32,
        min_pixels: f32,
    ) -> Self {
        Self {
            depth_index,
            source_index,
            sampler_index,
            projection,
            texel,
            extent,
            project,
            depth_params,
            radius,
            intensity,
            slices,
            steps,
            falloff,
            min_pixels,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<AoPush>() == 72);
    assert!(core::mem::offset_of!(AoPush, depth_index) == 0);
    assert!(core::mem::offset_of!(AoPush, source_index) == 4);
    assert!(core::mem::offset_of!(AoPush, sampler_index) == 8);
    assert!(core::mem::offset_of!(AoPush, projection) == 12);
    assert!(core::mem::offset_of!(AoPush, texel) == 16);
    assert!(core::mem::offset_of!(AoPush, extent) == 24);
    assert!(core::mem::offset_of!(AoPush, project) == 32);
    assert!(core::mem::offset_of!(AoPush, depth_params) == 40);
    assert!(core::mem::offset_of!(AoPush, radius) == 48);
    assert!(core::mem::offset_of!(AoPush, intensity) == 52);
    assert!(core::mem::offset_of!(AoPush, slices) == 56);
    assert!(core::mem::offset_of!(AoPush, steps) == 60);
    assert!(core::mem::offset_of!(AoPush, falloff) == 64);
    assert!(core::mem::offset_of!(AoPush, min_pixels) == 68);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("ao.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("ao.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_blur` (fragment).
pub static FS_BLUR_SPIRV: &[u8] = include_bytes!("ao.fs_blur.spv");
/// The `OpEntryPoint` name inside [`FS_BLUR_SPIRV`].
pub const FS_BLUR_ENTRY: &str = "main";
