// @generated by `cargo xtask shaders` from shaders/debug.slang — do not edit.
// source-hash: sha256:4c4f00bb006505f4a54c060b01c0e88ff6f3996e39735170c9c1a6c6fc81b71c generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `DebugPush` — std430 layout, 48 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct DebugPush {
    /// offset 0
    pub source_index: u32,
    /// offset 4
    pub sampler_index: u32,
    /// offset 8
    pub mode: u32,
    /// offset 12
    pub projection: u32,
    /// offset 16
    pub texel: [f32; 2],
    /// offset 24
    pub project: [f32; 2],
    /// offset 32
    pub depth_params: [f32; 2],
    /// offset 40
    pub scale: f32,
    /// offset 44
    pub exposure: f32,
}

impl DebugPush {
    /// Construct with every padding byte zeroed.
    #[expect(
        clippy::too_many_arguments,
        reason = "one field per push-constant member; the shader decides how many"
    )]
    pub fn new(
        source_index: u32,
        sampler_index: u32,
        mode: u32,
        projection: u32,
        texel: [f32; 2],
        project: [f32; 2],
        depth_params: [f32; 2],
        scale: f32,
        exposure: f32,
    ) -> Self {
        Self {
            source_index,
            sampler_index,
            mode,
            projection,
            texel,
            project,
            depth_params,
            scale,
            exposure,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<DebugPush>() == 48);
    assert!(core::mem::offset_of!(DebugPush, source_index) == 0);
    assert!(core::mem::offset_of!(DebugPush, sampler_index) == 4);
    assert!(core::mem::offset_of!(DebugPush, mode) == 8);
    assert!(core::mem::offset_of!(DebugPush, projection) == 12);
    assert!(core::mem::offset_of!(DebugPush, texel) == 16);
    assert!(core::mem::offset_of!(DebugPush, project) == 24);
    assert!(core::mem::offset_of!(DebugPush, depth_params) == 32);
    assert!(core::mem::offset_of!(DebugPush, scale) == 40);
    assert!(core::mem::offset_of!(DebugPush, exposure) == 44);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("debug.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("debug.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
