// @generated by `cargo xtask shaders` from shaders/debug.slang — do not edit.
// source-hash: sha256:dd4265f9d5ba1ad4bf92a9c224c92349fb4957db8b7aa6f9310a631c869c367b generator: v6
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `DebugPush` — std430 layout, 88 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct DebugPush {
    /// offset 0
    pub source_index: u32,
    /// offset 4
    pub sampler_index: u32,
    /// offset 8
    pub mode: u32,
    /// offset 12
    pub projection: u32,
    /// offset 16
    pub texel: [f32; 2],
    /// offset 24
    pub project: [f32; 2],
    /// offset 32
    pub depth_params: [f32; 2],
    /// offset 40
    pub fit_scale: [f32; 2],
    /// offset 48
    pub fit_bias: [f32; 2],
    /// offset 56
    pub fit_limit: [f32; 2],
    /// offset 64
    pub group: [u32; 2],
    /// offset 72
    pub scale: f32,
    /// offset 76
    pub exposure: f32,
    /// offset 80
    pub dither: f32,
    /// std430 tail padding — carries no data.
    pub _pad0: [u8; 4],
}

impl DebugPush {
    /// Construct with every padding byte zeroed.
    #[expect(
        clippy::too_many_arguments,
        reason = "one field per push-constant member; the shader decides how many"
    )]
    pub fn new(
        source_index: u32,
        sampler_index: u32,
        mode: u32,
        projection: u32,
        texel: [f32; 2],
        project: [f32; 2],
        depth_params: [f32; 2],
        fit_scale: [f32; 2],
        fit_bias: [f32; 2],
        fit_limit: [f32; 2],
        group: [u32; 2],
        scale: f32,
        exposure: f32,
        dither: f32,
    ) -> Self {
        Self {
            source_index,
            sampler_index,
            mode,
            projection,
            texel,
            project,
            depth_params,
            fit_scale,
            fit_bias,
            fit_limit,
            group,
            scale,
            exposure,
            dither,
            _pad0: [0; 4],
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<DebugPush>() == 88);
    assert!(core::mem::offset_of!(DebugPush, source_index) == 0);
    assert!(core::mem::offset_of!(DebugPush, sampler_index) == 4);
    assert!(core::mem::offset_of!(DebugPush, mode) == 8);
    assert!(core::mem::offset_of!(DebugPush, projection) == 12);
    assert!(core::mem::offset_of!(DebugPush, texel) == 16);
    assert!(core::mem::offset_of!(DebugPush, project) == 24);
    assert!(core::mem::offset_of!(DebugPush, depth_params) == 32);
    assert!(core::mem::offset_of!(DebugPush, fit_scale) == 40);
    assert!(core::mem::offset_of!(DebugPush, fit_bias) == 48);
    assert!(core::mem::offset_of!(DebugPush, fit_limit) == 56);
    assert!(core::mem::offset_of!(DebugPush, group) == 64);
    assert!(core::mem::offset_of!(DebugPush, scale) == 72);
    assert!(core::mem::offset_of!(DebugPush, exposure) == 76);
    assert!(core::mem::offset_of!(DebugPush, dither) == 80);
};

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const MODE_SCENE` in the shader source.
    pub const MODE_SCENE: u32 = 0;
    /// `static const MODE_DEPTH` in the shader source.
    pub const MODE_DEPTH: u32 = 1;
    /// `static const MODE_NORMAL` in the shader source.
    pub const MODE_NORMAL: u32 = 2;
    /// `static const MODE_RED` in the shader source.
    pub const MODE_RED: u32 = 3;
    /// `static const MODE_RGB` in the shader source.
    pub const MODE_RGB: u32 = 4;
}

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("debug.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("debug.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
