// @generated by `cargo xtask shaders` from shaders/include/depth.slang — do not edit.
// source-hash: sha256:5d87b7b91b453a2c4f687eb7f1ddaab5bd369e8dd99462afc978a508b71f0897 generator: v6
//
// The scalar constants this include declares, so a host imports the shader's
// number instead of restating it (PLAN.md §6 M86).

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const PROJECTION_PERSPECTIVE` in the shader source.
    pub const PROJECTION_PERSPECTIVE: u32 = 0;
    /// `static const PROJECTION_ORTHOGRAPHIC` in the shader source.
    pub const PROJECTION_ORTHOGRAPHIC: u32 = 1;
}
