// @generated by `cargo xtask shaders` from shaders/include/dither.slang — do not edit.
// source-hash: sha256:6accb3f53a403d91679923e20e3970a72d8d59b7eeef90de218f1e71cdacdc5a generator: v6
//
// The scalar constants this include declares, so a host imports the shader's
// number instead of restating it (PLAN.md §6 M86).

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const DITHER_DEADZONE` in the shader source.
    pub const DITHER_DEADZONE: f32 = 0.25;
}
