// @generated by `cargo xtask shaders` from shaders/include/pbr.slang — do not edit.
// source-hash: sha256:6bff1876e318dbad1393f61d1bffa6d6f9ba114961047d1023f702057b5a6476 generator: v6
//
// The scalar constants this include declares, so a host imports the shader's
// number instead of restating it (PLAN.md §6 M86).

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const PI` in the shader source.
    pub const PI: f32 = 3.14159265358979323846;
    /// `static const LIGHT_DIRECTIONAL` in the shader source.
    pub const LIGHT_DIRECTIONAL: u32 = 0;
    /// `static const LIGHT_POINT` in the shader source.
    pub const LIGHT_POINT: u32 = 1;
    /// `static const FRAME_STRIDE` in the shader source.
    pub const FRAME_STRIDE: u32 = 4440;
    /// `static const LIGHT_STRIDE` in the shader source.
    pub const LIGHT_STRIDE: u32 = 48;
    /// `static const CASCADE_STRIDE` in the shader source.
    pub const CASCADE_STRIDE: u32 = 80;
    /// `static const CASCADE_BASE` in the shader source.
    pub const CASCADE_BASE: u32 = 1048;
    /// `static const SH_COEFFICIENTS` in the shader source.
    pub const SH_COEFFICIENTS: u32 = 9;
    /// `static const MAX_SKY` in the shader source.
    pub const MAX_SKY: u32 = 4;
    /// `static const ENV_STRIDE` in the shader source.
    pub const ENV_STRIDE: u32 = 192;
    /// `static const SAMPLER_LINEAR_CLAMP` in the shader source.
    pub const SAMPLER_LINEAR_CLAMP: u32 = 1;
    /// `static const ENV_BASE` in the shader source.
    pub const ENV_BASE: u32 = 280;
    /// `static const MAX_CASCADES` in the shader source.
    pub const MAX_CASCADES: u32 = 4;
    /// `static const MAX_LAMPS` in the shader source.
    pub const MAX_LAMPS: u32 = 8;
    /// `static const LAMP_FACES` in the shader source.
    pub const LAMP_FACES: u32 = 6;
    /// `static const LAMP_STRIDE` in the shader source.
    pub const LAMP_STRIDE: u32 = 384;
    /// `static const LAMP_BASE` in the shader source.
    pub const LAMP_BASE: u32 = 1368;
    /// `static const PROBE_FACES` in the shader source.
    pub const PROBE_FACES: u32 = 6;
    /// `static const PROBE_SLOT_STRIDE` in the shader source.
    pub const PROBE_SLOT_STRIDE: u32 = 400;
    /// `static const PROBE_SH_TEXELS` in the shader source.
    pub const PROBE_SH_TEXELS: u32 = 4;
    /// `static const PROBE_STATE_TEXEL` in the shader source.
    pub const PROBE_STATE_TEXEL: u32 = 3;
    /// `static const PROBE_MOMENT_BORDER` in the shader source.
    pub const PROBE_MOMENT_BORDER: u32 = 1;
    /// `static const CLUSTER_X` in the shader source.
    pub const CLUSTER_X: u32 = 16;
    /// `static const CLUSTER_Y` in the shader source.
    pub const CLUSTER_Y: u32 = 8;
    /// `static const CLUSTER_Z` in the shader source.
    pub const CLUSTER_Z: u32 = 24;
    /// `static const MAX_LIGHTS` in the shader source.
    pub const MAX_LIGHTS: u32 = 260;
    /// `static const SHADOW_PLANE_SLOPE_LIMIT` in the shader source.
    pub const SHADOW_PLANE_SLOPE_LIMIT: f32 = 8.0;
    /// `static const SHADING_MULTISCATTER` in the shader source.
    pub const SHADING_MULTISCATTER: u32 = 1;
    /// `static const SHADING_LOBE` in the shader source.
    pub const SHADING_LOBE: u32 = 2;
    /// `static const SHADING_LUT` in the shader source.
    pub const SHADING_LUT: u32 = 4;
    /// `static const SHADING_AO` in the shader source.
    pub const SHADING_AO: u32 = 8;
    /// `static const SHADING_GI` in the shader source.
    pub const SHADING_GI: u32 = 16;
    /// `static const SHADING_FACING` in the shader source.
    pub const SHADING_FACING: u32 = 32;
    /// `static const SHADING_FIELD` in the shader source.
    pub const SHADING_FIELD: u32 = 64;
    /// `static const SHADING_TERM` in the shader source.
    pub const SHADING_TERM: u32 = 128;
    /// `static const SHADING_GI_FILTER` in the shader source.
    pub const SHADING_GI_FILTER: u32 = 256;
    /// `static const SPLIT_SUM_EXTENT` in the shader source.
    pub const SPLIT_SUM_EXTENT: u32 = 16;
    /// `static const VOGEL_COS` in the shader source.
    pub const VOGEL_COS: f32 = -0.73736888;
    /// `static const VOGEL_SIN` in the shader source.
    pub const VOGEL_SIN: f32 = 0.67549029;
    /// `static const LAMP_FILTER_RADIUS` in the shader source.
    pub const LAMP_FILTER_RADIUS: f32 = 1.5;
}
