// @generated by `cargo xtask shaders` from shaders/post.slang — do not edit.
// source-hash: sha256:01cab91dbf264bbb93c2296132a07d11f332200d1cc5418d29f4b7942c590932 generator: v4
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `PostPush` — std430 layout, 8 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PostPush {
    /// offset 0
    pub texture_index: u32,
    /// offset 4
    pub sampler_index: u32,
}

impl PostPush {
    /// Construct with every padding byte zeroed.
    pub fn new(texture_index: u32, sampler_index: u32) -> Self {
        Self {
            texture_index,
            sampler_index,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<PostPush>() == 8);
    assert!(core::mem::offset_of!(PostPush, texture_index) == 0);
    assert!(core::mem::offset_of!(PostPush, sampler_index) == 4);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("post.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("post.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
