// @generated by `cargo xtask shaders` from shaders/post.slang — do not edit.
// source-hash: sha256:5633fca78aa6377db3834a6a2306f40aff90b73cae965c5b24abe6710d415b01 generator: v6
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `PostPush` — std430 layout, 40 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PostPush {
    /// offset 0
    pub texture_index: u32,
    /// offset 4
    pub sampler_index: u32,
    /// offset 8
    pub exposure: f32,
    /// offset 12
    pub aa: u32,
    /// offset 16
    pub texel: [f32; 2],
    /// offset 24
    pub dither: f32,
    /// offset 28
    pub output: u32,
    /// offset 32
    pub paper_white: f32,
    /// offset 36
    pub white: f32,
}

impl PostPush {
    /// Construct with every padding byte zeroed.
    #[expect(
        clippy::too_many_arguments,
        reason = "one field per push-constant member; the shader decides how many"
    )]
    pub fn new(
        texture_index: u32,
        sampler_index: u32,
        exposure: f32,
        aa: u32,
        texel: [f32; 2],
        dither: f32,
        output: u32,
        paper_white: f32,
        white: f32,
    ) -> Self {
        Self {
            texture_index,
            sampler_index,
            exposure,
            aa,
            texel,
            dither,
            output,
            paper_white,
            white,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<PostPush>() == 40);
    assert!(core::mem::offset_of!(PostPush, texture_index) == 0);
    assert!(core::mem::offset_of!(PostPush, sampler_index) == 4);
    assert!(core::mem::offset_of!(PostPush, exposure) == 8);
    assert!(core::mem::offset_of!(PostPush, aa) == 12);
    assert!(core::mem::offset_of!(PostPush, texel) == 16);
    assert!(core::mem::offset_of!(PostPush, dither) == 24);
    assert!(core::mem::offset_of!(PostPush, output) == 28);
    assert!(core::mem::offset_of!(PostPush, paper_white) == 32);
    assert!(core::mem::offset_of!(PostPush, white) == 36);
};

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const DESATURATION` in the shader source.
    pub const DESATURATION: f32 = 0.15;
    /// `static const FXAA_SPAN_MAX` in the shader source.
    pub const FXAA_SPAN_MAX: f32 = 8.0;
    /// `static const OUTPUT_SDR` in the shader source.
    pub const OUTPUT_SDR: u32 = 0;
    /// `static const OUTPUT_HDR10` in the shader source.
    pub const OUTPUT_HDR10: u32 = 1;
    /// `static const OUTPUT_SCRGB` in the shader source.
    pub const OUTPUT_SCRGB: u32 = 2;
    /// `static const SCRGB_NITS` in the shader source.
    pub const SCRGB_NITS: f32 = 80.0;
}

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("post.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("post.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_downsample` (fragment).
pub static FS_DOWNSAMPLE_SPIRV: &[u8] = include_bytes!("post.fs_downsample.spv");
/// The `OpEntryPoint` name inside [`FS_DOWNSAMPLE_SPIRV`].
pub const FS_DOWNSAMPLE_ENTRY: &str = "main";
