// @generated by `cargo xtask shaders` from shaders/post.slang — do not edit.
// source-hash: sha256:ea3c32534f671a8dc1e705775ac4c5a0511a9ad7bcc9eaa2b71ba5bd155bf294 generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `PostPush` — std430 layout, 16 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct PostPush {
    /// offset 0
    pub texture_index: u32,
    /// offset 4
    pub sampler_index: u32,
    /// offset 8
    pub exposure: f32,
    /// offset 12
    pub reserved: u32,
}

impl PostPush {
    /// Construct with every padding byte zeroed.
    pub fn new(texture_index: u32, sampler_index: u32, exposure: f32, reserved: u32) -> Self {
        Self {
            texture_index,
            sampler_index,
            exposure,
            reserved,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<PostPush>() == 16);
    assert!(core::mem::offset_of!(PostPush, texture_index) == 0);
    assert!(core::mem::offset_of!(PostPush, sampler_index) == 4);
    assert!(core::mem::offset_of!(PostPush, exposure) == 8);
    assert!(core::mem::offset_of!(PostPush, reserved) == 12);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("post.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("post.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_downsample` (fragment).
pub static FS_DOWNSAMPLE_SPIRV: &[u8] = include_bytes!("post.fs_downsample.spv");
/// The `OpEntryPoint` name inside [`FS_DOWNSAMPLE_SPIRV`].
pub const FS_DOWNSAMPLE_ENTRY: &str = "main";
