// @generated by `cargo xtask shaders` from shaders/probe.slang — do not edit.
// source-hash: sha256:e13899f2b156a8be1e2920bf1b5c59694fe21e5ac2ed02c58423085a1a2f46a6 generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `ProbePush` — std430 layout, 40 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ProbePush {
    /// offset 0
    pub frame: u64,
    /// offset 8
    pub atlas: u32,
    /// offset 12
    pub slot: u32,
    /// offset 16
    pub face_edge: u32,
    /// offset 20
    pub moment_edge: u32,
    /// offset 24
    pub origin: [u32; 2],
    /// offset 32
    pub distance_cap: f32,
    /// std430 tail padding — carries no data.
    pub _pad0: [u8; 4],
}

impl ProbePush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        frame: u64,
        atlas: u32,
        slot: u32,
        face_edge: u32,
        moment_edge: u32,
        origin: [u32; 2],
        distance_cap: f32,
    ) -> Self {
        Self {
            frame,
            atlas,
            slot,
            face_edge,
            moment_edge,
            origin,
            distance_cap,
            _pad0: [0; 4],
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<ProbePush>() == 40);
    assert!(core::mem::offset_of!(ProbePush, frame) == 0);
    assert!(core::mem::offset_of!(ProbePush, atlas) == 8);
    assert!(core::mem::offset_of!(ProbePush, slot) == 12);
    assert!(core::mem::offset_of!(ProbePush, face_edge) == 16);
    assert!(core::mem::offset_of!(ProbePush, moment_edge) == 20);
    assert!(core::mem::offset_of!(ProbePush, origin) == 24);
    assert!(core::mem::offset_of!(ProbePush, distance_cap) == 32);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("probe.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_sh` (fragment).
pub static FS_SH_SPIRV: &[u8] = include_bytes!("probe.fs_sh.spv");
/// The `OpEntryPoint` name inside [`FS_SH_SPIRV`].
pub const FS_SH_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_moments` (fragment).
pub static FS_MOMENTS_SPIRV: &[u8] = include_bytes!("probe.fs_moments.spv");
/// The `OpEntryPoint` name inside [`FS_MOMENTS_SPIRV`].
pub const FS_MOMENTS_ENTRY: &str = "main";
