// @generated by `cargo xtask shaders` from shaders/scene.slang — do not edit.
// source-hash: sha256:cf813a59bb13c55d10b471fe4284ff80a7a48f6b9270e5747efa5032bdfae973 generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `ScenePush` — std430 layout, 56 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ScenePush {
    /// offset 0
    pub instances: u64,
    /// offset 8
    pub vertices: u64,
    /// offset 16
    pub frame: u64,
    /// offset 24
    pub instance_base: u32,
    /// offset 28
    pub base_color: u32,
    /// offset 32
    pub normal_map: u32,
    /// offset 36
    pub metallic_rough: u32,
    /// offset 40
    pub occlusion: u32,
    /// offset 44
    pub sampler_index: u32,
    /// offset 48
    pub metallic: f32,
    /// offset 52
    pub roughness: f32,
}

impl ScenePush {
    /// Construct with every padding byte zeroed.
    #[expect(
        clippy::too_many_arguments,
        reason = "one field per push-constant member; the shader decides how many"
    )]
    pub fn new(
        instances: u64,
        vertices: u64,
        frame: u64,
        instance_base: u32,
        base_color: u32,
        normal_map: u32,
        metallic_rough: u32,
        occlusion: u32,
        sampler_index: u32,
        metallic: f32,
        roughness: f32,
    ) -> Self {
        Self {
            instances,
            vertices,
            frame,
            instance_base,
            base_color,
            normal_map,
            metallic_rough,
            occlusion,
            sampler_index,
            metallic,
            roughness,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<ScenePush>() == 56);
    assert!(core::mem::offset_of!(ScenePush, instances) == 0);
    assert!(core::mem::offset_of!(ScenePush, vertices) == 8);
    assert!(core::mem::offset_of!(ScenePush, frame) == 16);
    assert!(core::mem::offset_of!(ScenePush, instance_base) == 24);
    assert!(core::mem::offset_of!(ScenePush, base_color) == 28);
    assert!(core::mem::offset_of!(ScenePush, normal_map) == 32);
    assert!(core::mem::offset_of!(ScenePush, metallic_rough) == 36);
    assert!(core::mem::offset_of!(ScenePush, occlusion) == 40);
    assert!(core::mem::offset_of!(ScenePush, sampler_index) == 44);
    assert!(core::mem::offset_of!(ScenePush, metallic) == 48);
    assert!(core::mem::offset_of!(ScenePush, roughness) == 52);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("scene.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("scene.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_depth` (vertex).
pub static VS_DEPTH_SPIRV: &[u8] = include_bytes!("scene.vs_depth.spv");
/// The `OpEntryPoint` name inside [`VS_DEPTH_SPIRV`].
pub const VS_DEPTH_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_shadow` (vertex).
pub static VS_SHADOW_SPIRV: &[u8] = include_bytes!("scene.vs_shadow.spv");
/// The `OpEntryPoint` name inside [`VS_SHADOW_SPIRV`].
pub const VS_SHADOW_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_depth` (fragment).
pub static FS_DEPTH_SPIRV: &[u8] = include_bytes!("scene.fs_depth.spv");
/// The `OpEntryPoint` name inside [`FS_DEPTH_SPIRV`].
pub const FS_DEPTH_ENTRY: &str = "main";
