// @generated by `cargo xtask shaders` from shaders/scene.slang — do not edit.
// source-hash: sha256:c90bd55ee8eaaddc475873fa9004dca74ac3a7a1a324c92c17c73e675052f299 generator: v4
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `ScenePush` — std430 layout, 32 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ScenePush {
    /// offset 0
    pub instances: u64,
    /// offset 8
    pub vertices: u64,
    /// offset 16
    pub instance_base: u32,
    /// offset 20
    pub texture_index: u32,
    /// offset 24
    pub sampler_index: u32,
    /// offset 28
    pub reserved: u32,
}

impl ScenePush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        instances: u64,
        vertices: u64,
        instance_base: u32,
        texture_index: u32,
        sampler_index: u32,
        reserved: u32,
    ) -> Self {
        Self {
            instances,
            vertices,
            instance_base,
            texture_index,
            sampler_index,
            reserved,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<ScenePush>() == 32);
    assert!(core::mem::offset_of!(ScenePush, instances) == 0);
    assert!(core::mem::offset_of!(ScenePush, vertices) == 8);
    assert!(core::mem::offset_of!(ScenePush, instance_base) == 16);
    assert!(core::mem::offset_of!(ScenePush, texture_index) == 20);
    assert!(core::mem::offset_of!(ScenePush, sampler_index) == 24);
    assert!(core::mem::offset_of!(ScenePush, reserved) == 28);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("scene.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("scene.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_depth` (vertex).
pub static VS_DEPTH_SPIRV: &[u8] = include_bytes!("scene.vs_depth.spv");
/// The `OpEntryPoint` name inside [`VS_DEPTH_SPIRV`].
pub const VS_DEPTH_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_depth` (fragment).
pub static FS_DEPTH_SPIRV: &[u8] = include_bytes!("scene.fs_depth.spv");
/// The `OpEntryPoint` name inside [`FS_DEPTH_SPIRV`].
pub const FS_DEPTH_ENTRY: &str = "main";
