// @generated by `cargo xtask shaders` from shaders/scene.slang — do not edit.
// source-hash: sha256:8d1132f06b6bf203759a754152b24ad34063b671e5907149605f83de7c1e4e8e generator: v4
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `ScenePush` — std430 layout, 128 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct ScenePush {
    /// offset 0
    pub mvp: [[f32; 4]; 4],
    /// offset 64
    pub vertices: u64,
    /// std430 padding — carries no data.
    pub _pad0: [u8; 8],
    /// offset 80
    pub tint: [f32; 4],
    /// offset 96
    pub rotation: [f32; 4],
    /// offset 112
    pub texture_index: u32,
    /// offset 116
    pub sampler_index: u32,
    /// std430 tail padding — carries no data.
    pub _pad1: [u8; 8],
}

impl ScenePush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        mvp: [[f32; 4]; 4],
        vertices: u64,
        tint: [f32; 4],
        rotation: [f32; 4],
        texture_index: u32,
        sampler_index: u32,
    ) -> Self {
        Self {
            mvp,
            vertices,
            _pad0: [0; 8],
            tint,
            rotation,
            texture_index,
            sampler_index,
            _pad1: [0; 8],
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<ScenePush>() == 128);
    assert!(core::mem::offset_of!(ScenePush, mvp) == 0);
    assert!(core::mem::offset_of!(ScenePush, vertices) == 64);
    assert!(core::mem::offset_of!(ScenePush, tint) == 80);
    assert!(core::mem::offset_of!(ScenePush, rotation) == 96);
    assert!(core::mem::offset_of!(ScenePush, texture_index) == 112);
    assert!(core::mem::offset_of!(ScenePush, sampler_index) == 116);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("scene.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("scene.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_depth` (vertex).
pub static VS_DEPTH_SPIRV: &[u8] = include_bytes!("scene.vs_depth.spv");
/// The `OpEntryPoint` name inside [`VS_DEPTH_SPIRV`].
pub const VS_DEPTH_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_depth` (fragment).
pub static FS_DEPTH_SPIRV: &[u8] = include_bytes!("scene.fs_depth.spv");
/// The `OpEntryPoint` name inside [`FS_DEPTH_SPIRV`].
pub const FS_DEPTH_ENTRY: &str = "main";
