// @generated by `cargo xtask shaders` from shaders/skybox.slang — do not edit.
// source-hash: sha256:51e01df2c91fe97cc75ad168143e4d5f2ee22685e5f88ea3dbe0e3fcd0894fcd generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `SkyPush` — std430 layout, 112 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SkyPush {
    /// offset 0
    pub inverse_view_projection: [[f32; 4]; 4],
    /// offset 64
    pub zenith: [f32; 4],
    /// offset 80
    pub horizon: [f32; 4],
    /// offset 96
    pub ground: [f32; 4],
}

impl SkyPush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        inverse_view_projection: [[f32; 4]; 4],
        zenith: [f32; 4],
        horizon: [f32; 4],
        ground: [f32; 4],
    ) -> Self {
        Self {
            inverse_view_projection,
            zenith,
            horizon,
            ground,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<SkyPush>() == 112);
    assert!(core::mem::offset_of!(SkyPush, inverse_view_projection) == 0);
    assert!(core::mem::offset_of!(SkyPush, zenith) == 64);
    assert!(core::mem::offset_of!(SkyPush, horizon) == 80);
    assert!(core::mem::offset_of!(SkyPush, ground) == 96);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("skybox.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("skybox.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
