// @generated by `cargo xtask shaders` from shaders/skybox.slang — do not edit.
// source-hash: sha256:846ea4e874cd4347c455428e31239d659616bb938aa8a4b2124217ffd77549ad generator: v5
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `SkyPush` — std430 layout, 128 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct SkyPush {
    /// offset 0
    pub inverse_view_projection: [[f32; 4]; 4],
    /// offset 64
    pub zenith: [f32; 4],
    /// offset 80
    pub horizon: [f32; 4],
    /// offset 96
    pub ground: [f32; 4],
    /// offset 112
    pub frame: u64,
    /// offset 120
    pub environment: u32,
    /// offset 124
    pub weight: f32,
}

impl SkyPush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        inverse_view_projection: [[f32; 4]; 4],
        zenith: [f32; 4],
        horizon: [f32; 4],
        ground: [f32; 4],
        frame: u64,
        environment: u32,
        weight: f32,
    ) -> Self {
        Self {
            inverse_view_projection,
            zenith,
            horizon,
            ground,
            frame,
            environment,
            weight,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<SkyPush>() == 128);
    assert!(core::mem::offset_of!(SkyPush, inverse_view_projection) == 0);
    assert!(core::mem::offset_of!(SkyPush, zenith) == 64);
    assert!(core::mem::offset_of!(SkyPush, horizon) == 80);
    assert!(core::mem::offset_of!(SkyPush, ground) == 96);
    assert!(core::mem::offset_of!(SkyPush, frame) == 112);
    assert!(core::mem::offset_of!(SkyPush, environment) == 120);
    assert!(core::mem::offset_of!(SkyPush, weight) == 124);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("skybox.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("skybox.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
