// @generated by `cargo xtask shaders` from shaders/ugly.slang — do not edit.
// source-hash: sha256:c15adf83b5d5e4e2caed474435b634c86498d71ae56f6b8824c014f24cf6b267 generator: v4
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `UglyPush` — std430 layout, 112 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UglyPush {
    /// offset 0
    pub mvp: [[f32; 4]; 4],
    /// offset 64
    pub vertices: u64,
    /// std430 padding — carries no data.
    pub _pad0: [u8; 8],
    /// offset 80
    pub tint: [f32; 4],
    /// offset 96
    pub rotation: [f32; 4],
}

impl UglyPush {
    /// Construct with every padding byte zeroed.
    pub fn new(mvp: [[f32; 4]; 4], vertices: u64, tint: [f32; 4], rotation: [f32; 4]) -> Self {
        Self {
            mvp,
            vertices,
            _pad0: [0; 8],
            tint,
            rotation,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<UglyPush>() == 112);
    assert!(core::mem::offset_of!(UglyPush, mvp) == 0);
    assert!(core::mem::offset_of!(UglyPush, vertices) == 64);
    assert!(core::mem::offset_of!(UglyPush, tint) == 80);
    assert!(core::mem::offset_of!(UglyPush, rotation) == 96);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("ugly.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("ugly.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_depth` (vertex).
pub static VS_DEPTH_SPIRV: &[u8] = include_bytes!("ugly.vs_depth.spv");
/// The `OpEntryPoint` name inside [`VS_DEPTH_SPIRV`].
pub const VS_DEPTH_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_depth` (fragment).
pub static FS_DEPTH_SPIRV: &[u8] = include_bytes!("ugly.fs_depth.spv");
/// The `OpEntryPoint` name inside [`FS_DEPTH_SPIRV`].
pub const FS_DEPTH_ENTRY: &str = "main";
