// @generated by `cargo xtask shaders` from shaders/ugly.slang — do not edit.
// source-hash: sha256:2bbb5f65583f55f7bbd2a8df4ba9c72bc65d2e79348c8293bd2d7dad9a6e64cf generator: v6
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `UglyPush` — std430 layout, 112 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UglyPush {
    /// offset 0
    pub vertices: u64,
    /// offset 8
    pub frame: u64,
    /// offset 16
    pub tint: [f32; 4],
    /// offset 32
    pub rotation: [f32; 4],
    /// offset 48
    pub offset: [f32; 4],
    /// offset 64
    pub scale: [f32; 4],
    /// offset 80
    pub material: [f32; 4],
    /// offset 96
    pub shadow_view: u32,
    /// std430 tail padding — carries no data.
    pub _pad0: [u8; 12],
}

impl UglyPush {
    /// Construct with every padding byte zeroed.
    #[expect(
        clippy::too_many_arguments,
        reason = "one field per push-constant member; the shader decides how many"
    )]
    pub fn new(
        vertices: u64,
        frame: u64,
        tint: [f32; 4],
        rotation: [f32; 4],
        offset: [f32; 4],
        scale: [f32; 4],
        material: [f32; 4],
        shadow_view: u32,
    ) -> Self {
        Self {
            vertices,
            frame,
            tint,
            rotation,
            offset,
            scale,
            material,
            shadow_view,
            _pad0: [0; 12],
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<UglyPush>() == 112);
    assert!(core::mem::offset_of!(UglyPush, vertices) == 0);
    assert!(core::mem::offset_of!(UglyPush, frame) == 8);
    assert!(core::mem::offset_of!(UglyPush, tint) == 16);
    assert!(core::mem::offset_of!(UglyPush, rotation) == 32);
    assert!(core::mem::offset_of!(UglyPush, offset) == 48);
    assert!(core::mem::offset_of!(UglyPush, scale) == 64);
    assert!(core::mem::offset_of!(UglyPush, material) == 80);
    assert!(core::mem::offset_of!(UglyPush, shadow_view) == 96);
};

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const VERTEX_STRIDE` in the shader source.
    pub const VERTEX_STRIDE: u32 = 24;
}

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("ugly.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("ugly.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_depth` (vertex).
pub static VS_DEPTH_SPIRV: &[u8] = include_bytes!("ugly.vs_depth.spv");
/// The `OpEntryPoint` name inside [`VS_DEPTH_SPIRV`].
pub const VS_DEPTH_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_probe` (vertex).
pub static VS_PROBE_SPIRV: &[u8] = include_bytes!("ugly.vs_probe.spv");
/// The `OpEntryPoint` name inside [`VS_PROBE_SPIRV`].
pub const VS_PROBE_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_probe` (fragment).
pub static FS_PROBE_SPIRV: &[u8] = include_bytes!("ugly.fs_probe.spv");
/// The `OpEntryPoint` name inside [`FS_PROBE_SPIRV`].
pub const FS_PROBE_ENTRY: &str = "main";

/// SPIR-V for entry point `vs_shadow` (vertex).
pub static VS_SHADOW_SPIRV: &[u8] = include_bytes!("ugly.vs_shadow.spv");
/// The `OpEntryPoint` name inside [`VS_SHADOW_SPIRV`].
pub const VS_SHADOW_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_depth` (fragment).
pub static FS_DEPTH_SPIRV: &[u8] = include_bytes!("ugly.fs_depth.spv");
/// The `OpEntryPoint` name inside [`FS_DEPTH_SPIRV`].
pub const FS_DEPTH_ENTRY: &str = "main";
