// @generated by `cargo xtask shaders` from shaders/ui.slang — do not edit.
// source-hash: sha256:4d918d3d5889665c861bb35d3bf28ecc718da76f9dc1cf4571024b75dac0604c generator: v6
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `UiPush` — std430 layout, 24 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct UiPush {
    /// offset 0
    pub vertices: u64,
    /// offset 8
    pub texture_index: u32,
    /// offset 12
    pub sampler_index: u32,
    /// offset 16
    pub inv_extent: [f32; 2],
}

impl UiPush {
    /// Construct with every padding byte zeroed.
    pub fn new(
        vertices: u64,
        texture_index: u32,
        sampler_index: u32,
        inv_extent: [f32; 2],
    ) -> Self {
        Self {
            vertices,
            texture_index,
            sampler_index,
            inv_extent,
        }
    }
}

const _: () = {
    assert!(core::mem::size_of::<UiPush>() == 24);
    assert!(core::mem::offset_of!(UiPush, vertices) == 0);
    assert!(core::mem::offset_of!(UiPush, texture_index) == 8);
    assert!(core::mem::offset_of!(UiPush, sampler_index) == 12);
    assert!(core::mem::offset_of!(UiPush, inv_extent) == 16);
};

/// The shader's own scalar constants (§6 M86) — one number, not two.
#[allow(dead_code, reason = "a host wants some of these, not all")]
#[allow(
    clippy::approx_constant,
    clippy::excessive_precision,
    reason = "the shader's literal is the number; restating it here would make two again"
)]
pub mod consts {
    /// `static const UI_VERTEX_STRIDE` in the shader source.
    pub const UI_VERTEX_STRIDE: u32 = 20;
}

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("ui.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("ui.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
