//! `gg-render` (§4.5) — the render graph, and the passes over it.
//!
//! The graph is [`graph`]: passes declare virtual resources and usages, and
//! every `synchronization2` barrier and layout transition in a frame is derived
//! from those declarations rather than written by hand. That derivation's
//! Vulkan half lives behind the §3 seam in `gg-rhi`; this side names no stage,
//! no access mask and no layout.
//!
//! [`Renderer`] is the graph put to work for the shell: depth prepass → forward
//! opaque → fullscreen post → present, the §4.5 v1 list minus the readback pass,
//! which is a harness's business rather than a window's. The three calls the
//! shell makes ([`Renderer::new`], [`Renderer::frame`], [`Renderer::shutdown`])
//! are the same three it made at M5 — that was the part meant to survive.
//!
//! It draws exactly one primitive — a box — because the game says where, how big
//! and what colour, and nothing else (`gg_ecs::boundary::Renderable`). A
//! renderer with more opinions than that would be a renderer the Ugly Game
//! cannot restyle without rebuilding the engine, which is the wrong half of the
//! cooperative loop to make expensive.

#![warn(missing_docs)]

pub mod content;
pub mod cvars;
pub mod graph;
pub mod residency;
mod scene;
pub mod ui;

/// Generated by `cargo xtask shaders` from `shaders/*.slang` (§4.4).
pub mod shaders_gen {
    /// The fullscreen post pass.
    pub mod post;
    /// The pack pass: mesh geometry and a base-colour map (§4.6).
    pub mod scene;
    /// The forward pass and the depth prepass: push constants + embedded SPIR-V.
    pub mod ugly;
    /// The UI layer's one pipeline.
    pub mod ui;
}

use std::path::Path;

use content::{Content, ContentError};
use gg_assets::AssetId;
use gg_extract::{Extracted, Instance, Scenes};
use gg_math::render;
use gg_rhi::{
    Blend, BufferDesc, BufferHandle, BufferKind, ColorTarget, DepthMode, DeviceAddress,
    DeviceReport, DrawSpec, FrameOutcome, FrameStart, GpuClock, GraphContext, ImageDesc,
    ImageFormat, ImageHandle, MemoryUse, PassTiming, PipelineDesc, PipelineHandle, Rhi, RhiError,
    Sampler, ShutdownReport, TextureIndex,
};
use graph::{Body, Declared, DepthUse, Load, Transients};
use raw_window_handle::{HasDisplayHandle, HasWindowHandle};
use scene::ScenePass;
use shaders_gen::post as post_shader;
use shaders_gen::ugly as shader;

/// One vertex, mirroring `ugly.slang`'s `VERTEX_STRIDE` byte layout. The shader
/// reads these at hardcoded offsets through a device address, so the layout is
/// frozen below rather than trusted.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct Vertex {
    position: [f32; 3],
    normal: [f32; 3],
}

const _: () = {
    assert!(core::mem::size_of::<Vertex>() == 24);
    assert!(core::mem::offset_of!(Vertex, normal) == 12);
};

/// Where the frame is seen from, on the render side of the membrane.
///
/// Position is absent on purpose: it never crosses. [`Extracted`] arrives
/// already camera-relative, so the eye *is* the origin here and the view matrix
/// carries rotation only — which is what makes a camera 10^12 m out render
/// without jitter (§1.4, §4.2.1).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct View {
    /// Rotation about +Y, radians.
    pub yaw: f32,
    /// Rotation about the camera's right axis, radians.
    pub pitch: f32,
    /// Vertical field of view, radians.
    pub fov_y: f32,
    /// Near plane. With reverse-Z and an infinite far plane this is the *only*
    /// depth-precision knob there is (§2, Math row).
    pub near: f32,
}

impl Default for View {
    /// Not a constant: `fov_y` and `near` are CVars (§4.8), so *rebuilding* a
    /// `View` each frame is how a console edit reaches the screen — and a caller
    /// that keeps one instead has pinned them, deliberately.
    fn default() -> Self {
        View {
            yaw: 0.0,
            pitch: 0.0,
            fov_y: cvars::FOV.float() as f32,
            near: cvars::NEAR.float() as f32,
        }
    }
}

impl View {
    fn rotation(&self) -> render::Quat {
        // YXZ: yaw about world +Y first, then pitch about the rotated right
        // axis — the fly-camera order, and the one that never rolls.
        render::Quat::from_euler(render::EulerRot::YXZ, self.yaw, self.pitch, 0.0)
    }

    /// Camera-relative world → clip.
    fn view_projection(&self, extent: (u32, u32)) -> render::Mat4 {
        let rotation = self.rotation();
        let aspect = extent.0.max(1) as f32 / extent.1.max(1) as f32;
        let view = render::camera::rh::view::look_to_mat4(
            render::Vec3::ZERO,
            rotation * render::Vec3::NEG_Z,
            rotation * render::Vec3::Y,
        );
        render::perspective_reverse_z(self.fov_y, aspect, self.near) * view
    }
}

/// A window's GPU state and the passes over it — what the shell holds.
///
/// It owns the [`Rhi`] rather than taking one per call so the shell never names
/// `gg-rhi` at all: §3 caps the shell at zero engine logic, and a host that
/// creates pipelines is past that line whatever the line count says.
pub struct Renderer {
    rhi: Rhi,
    pass: BoxPass,
    scene: ScenePass,
    ui: ui::UiPass,
    transients: Transients,
    /// The pack, once a host has named one. `None` is a renderer that draws
    /// boxes and nothing else — which is every tier before M9 and every run
    /// without `--pack`.
    content: Option<Content>,
}

impl Renderer {
    /// Bring up the device and swapchain for `window`, and upload the pass.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses: no device, no surface, or a failed upload.
    ///
    /// # Safety of teardown
    ///
    /// The surface may not outlive the window it came from, so [`Renderer::shutdown`]
    /// must run while the window is still alive (§4.3).
    pub fn new(
        window: &(impl HasWindowHandle + HasDisplayHandle),
        extent: (u32, u32),
    ) -> Result<Self, RhiError> {
        let mut rhi = Rhi::new(window, extent)?;
        let pass = BoxPass::new(&mut rhi)?;
        let scene = ScenePass::new(&mut rhi)?;
        let ui = ui::UiPass::new(&mut rhi)?;
        Ok(Renderer {
            rhi,
            pass,
            scene,
            ui,
            transients: Transients::default(),
            content: None,
        })
    }

    /// Map a pack and start its load clock (§4.6). The game names what to draw
    /// out of it; this only says which file.
    ///
    /// # Errors
    /// A file that will not open, or a pack the loader refuses by name.
    pub fn open_pack(&mut self, path: &Path) -> Result<(), ContentError> {
        self.content = Some(Content::open(path)?);
        Ok(())
    }

    /// The pack, for a host reporting on its load (§6 M9's exit row).
    #[must_use]
    pub fn pack(&self) -> Option<&Content> {
        self.content.as_ref()
    }

    /// Re-open the pack now if it has been rewritten, rather than waiting for
    /// the frame that would notice (§4.6). `true` if it had been.
    ///
    /// # Errors
    /// A rewritten pack the loader refuses — leaving the old one playing.
    pub fn reload_pack(&mut self) -> Result<bool, ContentError> {
        match &mut self.content {
            Some(content) => content.poll_reload(&mut self.rhi),
            None => Ok(false),
        }
    }

    /// What [`gg_extract::Extracted::append_models`] expands scene assets
    /// through. A renderer with no pack expands nothing, so a host calls this
    /// unconditionally.
    #[must_use]
    pub fn scenes(&self) -> &dyn Scenes {
        match &self.content {
            Some(content) => content,
            None => &(),
        }
    }

    /// Hand the UI pass the coverage atlas its glyphs are cut from (§4.9).
    /// Called once, by whoever owns the font — this side never learns what a
    /// glyph is. Until it is called the UI pass draws nothing.
    ///
    /// # Errors
    ///
    /// A bitmap whose length disagrees with its extent, or an allocation.
    pub fn set_ui_atlas(&mut self, coverage: &ui::Coverage<'_>) -> Result<(), RhiError> {
        self.ui.set_atlas(&mut self.rhi, coverage)
    }

    /// Live buffer and image allocations — the overlay's memory row (§4.8).
    pub fn memory(&self) -> MemoryUse {
        self.rhi.memory()
    }

    /// Which device was chosen, and what it can do (§4.3).
    pub fn device(&self) -> &DeviceReport {
        self.rhi.device_report()
    }

    /// The size the next frame will render at, in physical pixels.
    pub fn extent(&self) -> (u32, u32) {
        self.rhi.swapchain_extent()
    }

    /// New window size in physical pixels. `(0, 0)` suspends rather than
    /// recreates.
    pub fn resize(&mut self, width: u32, height: u32) {
        self.rhi.resize(width, height);
    }

    /// Per-pass GPU milliseconds from the last retired frame (§4.8) — the rows
    /// the debug overlay draws. Empty in a build without the timestamps, or
    /// before the first frame comes back.
    pub fn pass_timings(&self) -> &[PassTiming] {
        self.rhi.pass_timings()
    }

    /// The device clock, for a profiler anchoring GPU spans to CPU time (§4.8).
    pub fn gpu_clock(&self) -> Option<GpuClock> {
        self.rhi.gpu_clock()
    }

    /// One frame through the graph: depth prepass, forward opaque, post, the UI
    /// layer over it, present.
    ///
    /// `ui` is this frame's whole UI layer as one batch (§4.9) — empty means no
    /// UI pass is declared at all, which is what a dist build with no overlay
    /// hands over every frame.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses while compiling, recording, submitting or
    /// presenting.
    pub fn frame(
        &mut self,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
        ui: &[ui::UiVertex],
    ) -> Result<FrameOutcome, RhiError> {
        // Before `begin_frame`, not inside it: uploads go to the transfer queue
        // through the staging ring and belong to no frame slot (§4.3).
        stream(&mut self.content, &mut self.rhi, extracted)?;
        let token = match self.rhi.begin_frame()? {
            FrameStart::Ready(token) => token,
            FrameStart::Skipped(outcome) => return Ok(outcome),
        };
        let extent = token.extent();
        self.pass.build(extent, extracted, view);
        self.scene
            .build(extent, extracted, view, self.content.as_ref());
        // After `begin_frame`, which is where this slot's previous frame is
        // waited out — the wait that makes writing its region safe.
        let slot = GraphContext::frame_slot(&self.rhi);
        self.ui.write(&mut self.rhi, slot, ui)?;
        let ui_push = self.ui.push(extent);

        let mut frame = self.transients.frame(&mut self.rhi, extent)?;
        let backbuffer = frame.backbuffer();
        let scene = frame.color("scene.color")?;
        let depth = frame.depth("scene.depth")?;
        let post_push = self.pass.post_push(&frame, scene)?;

        let prepass_draws = prepass_draws(&self.pass, &self.scene);
        let forward_draws = forward_draws(&self.pass, &self.scene);
        let post_draws = [self.pass.post_draw(&post_push)];
        let samples = [scene];
        let mut declared: Vec<Declared<'_>> = scene_graph(
            backbuffer,
            scene,
            depth,
            color,
            &prepass_draws,
            &forward_draws,
            &post_draws,
            &samples,
        )
        .into();
        let ui_draws: Vec<DrawSpec<'_>> = self.ui.draw(&ui_push).into_iter().collect();
        if !ui_draws.is_empty() {
            declared.push(ui_pass(backbuffer, &ui_draws));
        }
        let compiled = frame.compile(&declared)?;
        self.rhi.execute(token, &compiled.passes())
    }

    /// The graph the next frame will run, as text — `--dump-render-graph`
    /// (§4.5). Compiling it is what the frame does anyway, so what this prints
    /// is what runs.
    ///
    /// # Errors
    ///
    /// Whatever compiling the graph refuses.
    pub fn dump_graph(&mut self) -> Result<String, RhiError> {
        let extent = self.rhi.swapchain_extent();
        let mut frame = self.transients.frame(&mut self.rhi, extent)?;
        let backbuffer = frame.backbuffer();
        let scene = frame.color("scene.color")?;
        let depth = frame.depth("scene.depth")?;
        let post_push = self.pass.post_push(&frame, scene)?;
        let prepass_draws = prepass_draws(&self.pass, &self.scene);
        let forward_draws = forward_draws(&self.pass, &self.scene);
        let post_draws = [self.pass.post_draw(&post_push)];
        let samples = [scene];
        let mut declared: Vec<Declared<'_>> = scene_graph(
            backbuffer,
            scene,
            depth,
            [0.0; 4],
            &prepass_draws,
            &forward_draws,
            &post_draws,
            &samples,
        )
        .into();
        // The UI pass as the *last* frame declared it: what the next one draws
        // is not knowable here, and a dump that always omitted it would print a
        // graph the screen never runs.
        let ui_push = self.ui.push(extent);
        let ui_draws: Vec<DrawSpec<'_>> = self.ui.draw(&ui_push).into_iter().collect();
        if !ui_draws.is_empty() {
            declared.push(ui_pass(backbuffer, &ui_draws));
        }
        Ok(frame.compile(&declared)?.dump())
    }

    /// Release everything and account for it (§4.3, §5.4).
    pub fn shutdown(mut self) -> ShutdownReport {
        // A refusal here can only be a handle this struct did not issue, which
        // cannot happen — and if it somehow did, the unreleased memory shows up
        // in the report below, which is the check that actually matters.
        drop(self.transients.destroy(&mut self.rhi));
        if let Some(content) = &mut self.content {
            drop(content.destroy(&mut self.rhi));
        }
        drop(self.pass.destroy(&mut self.rhi));
        drop(self.scene.destroy(&mut self.rhi));
        drop(self.ui.destroy(&mut self.rhi));
        self.rhi.shutdown()
    }
}

/// One offscreen frame: the pixels, and the graph that produced them.
pub struct OffscreenFrame {
    /// RGBA8, tightly packed, `extent.0 * extent.1 * 4` bytes.
    pub pixels: Vec<u8>,
    /// The compiled graph as text (§4.5).
    pub dump: String,
    /// The passes handed to the RHI, in submission order — read off the
    /// executed list, not off the declaration, so it cannot drift from it.
    pub order: Vec<String>,
}

/// The v1 pass list with no window in it: the same [`BoxPass`] and the same
/// [`scene_graph`] the shell runs, with §4.5's readback pass appended where the
/// present would be.
///
/// This exists because the shell is windowed and therefore manual (§1.5), which
/// would otherwise leave the engine's own render path with no image coverage at
/// all. `gg-golden` renders through this, so the golden guards the frame the
/// screen gets rather than a lookalike assembled beside it.
pub struct OffscreenRenderer {
    rhi: gg_rhi::OffscreenRhi,
    pass: BoxPass,
    scene: ScenePass,
    ui: ui::UiPass,
    transients: Transients,
    readback: BufferHandle,
    extent: (u32, u32),
    content: Option<Content>,
}

impl OffscreenRenderer {
    /// Bring up a surfaceless device at `extent` and upload the pass.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses: no device, or a failed upload.
    pub fn new(extent: (u32, u32)) -> Result<Self, RhiError> {
        let mut rhi = gg_rhi::OffscreenRhi::new(extent)?;
        let pass = BoxPass::new(&mut rhi)?;
        let scene = ScenePass::new(&mut rhi)?;
        let ui = ui::UiPass::new(&mut rhi)?;
        // One buffer for the renderer's life: a frame that allocated its own
        // readback would be measuring the allocator as much as the frame.
        let readback = rhi.create_buffer(&BufferDesc {
            name: "render.offscreen.readback",
            size: u64::from(extent.0) * u64::from(extent.1) * 4,
            kind: BufferKind::Readback,
        })?;
        Ok(OffscreenRenderer {
            rhi,
            pass,
            scene,
            ui,
            transients: Transients::default(),
            readback,
            extent,
            content: None,
        })
    }

    /// Map a pack — see [`Renderer::open_pack`].
    ///
    /// # Errors
    /// A file that will not open, or a pack the loader refuses by name.
    pub fn open_pack(&mut self, path: &Path) -> Result<(), ContentError> {
        self.content = Some(Content::open(path)?);
        Ok(())
    }

    /// The pack — see [`Renderer::pack`].
    #[must_use]
    pub fn pack(&self) -> Option<&Content> {
        self.content.as_ref()
    }

    /// Re-open a rewritten pack — see [`Renderer::reload_pack`].
    ///
    /// # Errors
    /// A rewritten pack the loader refuses.
    pub fn reload_pack(&mut self) -> Result<bool, ContentError> {
        match &mut self.content {
            Some(content) => content.poll_reload(&mut self.rhi),
            None => Ok(false),
        }
    }

    /// Scene expansion — see [`Renderer::scenes`].
    #[must_use]
    pub fn scenes(&self) -> &dyn Scenes {
        match &self.content {
            Some(content) => content,
            None => &(),
        }
    }

    /// Hand the UI pass its coverage atlas — see [`Renderer::set_ui_atlas`].
    ///
    /// # Errors
    ///
    /// A bitmap whose length disagrees with its extent, or an allocation.
    pub fn set_ui_atlas(&mut self, coverage: &ui::Coverage<'_>) -> Result<(), RhiError> {
        self.ui.set_atlas(&mut self.rhi, coverage)
    }

    /// Live buffer and image allocations (§4.8).
    pub fn memory(&self) -> MemoryUse {
        self.rhi.memory()
    }

    /// Which device was chosen, and what it can do (§4.3).
    pub fn device(&self) -> &DeviceReport {
        self.rhi.device_report()
    }

    /// Per-pass GPU milliseconds from the last [`Self::frame`] (§4.8). Current
    /// rather than a frame behind: an offscreen render blocks until it retires.
    pub fn pass_timings(&self) -> &[PassTiming] {
        self.rhi.pass_timings()
    }

    /// One frame: depth prepass, forward opaque, post, the UI layer, readback.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses while compiling, recording or submitting.
    pub fn frame(
        &mut self,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
        ui: &[ui::UiVertex],
    ) -> Result<OffscreenFrame, RhiError> {
        stream(&mut self.content, &mut self.rhi, extracted)?;
        self.pass.build(self.extent, extracted, view);
        self.scene
            .build(self.extent, extracted, view, self.content.as_ref());
        // One slot and a blocking submit per frame here, so nothing is in
        // flight to race the write.
        self.ui.write(&mut self.rhi, 0, ui)?;
        let ui_push = self.ui.push(self.extent);
        let mut frame = self.transients.frame(&mut self.rhi, self.extent)?;
        let backbuffer = frame.backbuffer();
        let scene = frame.color("scene.color")?;
        let depth = frame.depth("scene.depth")?;
        let into = frame.readback_buffer("render.offscreen.readback", self.readback);
        let post_push = self.pass.post_push(&frame, scene)?;

        let prepass_draws = prepass_draws(&self.pass, &self.scene);
        let forward_draws = forward_draws(&self.pass, &self.scene);
        let post_draws = [self.pass.post_draw(&post_push)];
        let samples = [scene];
        let mut declared: Vec<Declared<'_>> = scene_graph(
            backbuffer,
            scene,
            depth,
            color,
            &prepass_draws,
            &forward_draws,
            &post_draws,
            &samples,
        )
        .into();
        let ui_draws: Vec<DrawSpec<'_>> = self.ui.draw(&ui_push).into_iter().collect();
        if !ui_draws.is_empty() {
            declared.push(ui_pass(backbuffer, &ui_draws));
        }
        // Readback last, so the image judged is the one the screen would get —
        // UI included (§4.10).
        declared.push(graph::readback_pass(backbuffer, into));

        let compiled = frame.compile(&declared)?;
        let dump = compiled.dump();
        let passes = compiled.passes();
        let order = passes.iter().map(|p| p.name.to_string()).collect();
        self.rhi.execute(&passes)?;
        Ok(OffscreenFrame {
            pixels: self.rhi.map_buffer(self.readback)?.to_vec(),
            dump,
            order,
        })
    }

    /// Release everything and report leaks and validation messages (§4.3).
    pub fn shutdown(mut self) -> ShutdownReport {
        drop(self.transients.destroy(&mut self.rhi));
        drop(self.rhi.destroy_buffer(self.readback));
        if let Some(content) = &mut self.content {
            drop(content.destroy(&mut self.rhi));
        }
        drop(self.pass.destroy(&mut self.rhi));
        drop(self.scene.destroy(&mut self.rhi));
        drop(self.ui.destroy(&mut self.rhi));
        self.rhi.shutdown()
    }
}

/// Ask the pack for what this frame names, and move some of it onto the device.
///
/// Shared by both entry points rather than written twice: a pack that streamed
/// differently offscreen would make the golden suite (§4.10) a gate on a path
/// the screen never takes.
fn stream(
    content: &mut Option<Content>,
    rhi: &mut impl GpuHost,
    extracted: &Extracted,
) -> Result<(), RhiError> {
    let Some(content) = content else {
        return Ok(());
    };
    // Requested from what the frame *shows*, not from a manifest: a scene id
    // pulls its meshes in with it, and an asset nothing draws is never read off
    // the disk at all.
    for instance in &extracted.models {
        content.request(AssetId(instance.asset));
    }
    // The watcher's other end (§4.6). Absent from dist rather than disabled —
    // there is no `ggc` there to rewrite the file.
    #[cfg(feature = "hot-reload")]
    if let Err(refused) = content.poll_reload(rhi) {
        // The old pack is still mapped and still playing; a broken rebuild
        // belongs in the terminal, not in the player's session.
        tracing::error!(error = %refused, "pack reload refused — still drawing the last good one");
    }
    let budget = cvars::UPLOAD_BUDGET.int().max(0) as usize;
    content.pump(rhi, budget)?;
    Ok(())
}

/// Boxes then pack meshes, as one list. Two pipelines inside one pass rather
/// than a pass each: they write the same attachments, so a second prepass would
/// be a second set of derived barriers around no new resource.
fn prepass_draws<'a>(pass: &'a BoxPass, scene: &'a ScenePass) -> Vec<DrawSpec<'a>> {
    let mut draws = pass.draws(pass.prepass);
    draws.extend(scene.draws(scene.prepass()));
    draws
}

fn forward_draws<'a>(pass: &'a BoxPass, scene: &'a ScenePass) -> Vec<DrawSpec<'a>> {
    let mut draws = pass.draws(pass.forward);
    draws.extend(scene.draws(scene.forward()));
    draws
}

/// The boxes, and the three pipelines that draw them: prepass, forward, post.
struct BoxPass {
    prepass: PipelineHandle,
    forward: PipelineHandle,
    post: PipelineHandle,
    vertices: BufferHandle,
    indices: BufferHandle,
    vertex_address: DeviceAddress,
    index_count: u32,
    /// Reused across frames. The push constants have to outlive the [`DrawSpec`]s
    /// that borrow them, and extract already refuses to allocate per frame — a
    /// buffer beside it that did would undo that.
    pushes: Vec<shader::UglyPush>,
}

/// The slice of an RHI a pass — or a resident asset — needs to put itself on
/// the GPU.
///
/// The same shape demo 02's `SceneHost` has, and for the same reason: §3 keeps
/// a backend abstraction out of `gg-rhi`, so a crate that wants to run one pass
/// over both entry points writes its own two-line bridge. What it buys here is
/// that the offscreen test builds the *same* pass the shell does, and that
/// [`Residency`](residency::Residency) uploads through the same one.
///
/// Every method forwards verbatim; see the like-named one on
/// [`Rhi`](gg_rhi::Rhi) for what each contracts and refuses.
pub trait GpuHost {
    /// See [`gg_rhi::Rhi::create_buffer`].
    fn create_buffer(&mut self, desc: &BufferDesc<'_>) -> Result<BufferHandle, RhiError>;
    /// See [`gg_rhi::Rhi::upload_buffer`].
    fn upload_buffer(&mut self, h: BufferHandle, offset: u64, b: &[u8]) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::write_buffer`].
    fn write_buffer(&mut self, h: BufferHandle, offset: u64, b: &[u8]) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::flush_uploads`].
    fn flush_uploads(&mut self) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::buffer_address`].
    fn buffer_address(&self, handle: BufferHandle) -> Result<DeviceAddress, RhiError>;
    /// See [`gg_rhi::Rhi::create_image`].
    fn create_image(&mut self, desc: &ImageDesc<'_>) -> Result<ImageHandle, RhiError>;
    /// See [`gg_rhi::Rhi::upload_image`].
    fn upload_image(
        &mut self,
        handle: ImageHandle,
        level: u32,
        bytes: &[u8],
    ) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::register_texture`].
    fn register_texture(&mut self, handle: ImageHandle) -> Result<TextureIndex, RhiError>;
    /// See [`gg_rhi::Rhi::create_pipeline`].
    fn create_pipeline(&mut self, desc: &PipelineDesc<'_>) -> Result<PipelineHandle, RhiError>;
    /// See [`gg_rhi::Rhi::destroy_pipeline`].
    fn destroy_pipeline(&mut self, handle: PipelineHandle) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::destroy_buffer`].
    fn destroy_buffer(&mut self, handle: BufferHandle) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::destroy_image`].
    fn destroy_image(&mut self, handle: ImageHandle) -> Result<(), RhiError>;
}

/// Both entry points, verbatim: the trait exists to name the overlap, not to
/// add behaviour to it.
macro_rules! pass_host {
    ($t:ty) => {
        impl GpuHost for $t {
            fn create_buffer(&mut self, desc: &BufferDesc<'_>) -> Result<BufferHandle, RhiError> {
                <$t>::create_buffer(self, desc)
            }
            fn upload_buffer(
                &mut self,
                h: BufferHandle,
                offset: u64,
                b: &[u8],
            ) -> Result<(), RhiError> {
                <$t>::upload_buffer(self, h, offset, b)
            }
            fn write_buffer(
                &mut self,
                h: BufferHandle,
                offset: u64,
                b: &[u8],
            ) -> Result<(), RhiError> {
                <$t>::write_buffer(self, h, offset, b)
            }
            fn flush_uploads(&mut self) -> Result<(), RhiError> {
                <$t>::flush_uploads(self)
            }
            fn buffer_address(&self, handle: BufferHandle) -> Result<DeviceAddress, RhiError> {
                <$t>::buffer_address(self, handle)
            }
            fn create_image(&mut self, desc: &ImageDesc<'_>) -> Result<ImageHandle, RhiError> {
                <$t>::create_image(self, desc)
            }
            fn upload_image(
                &mut self,
                handle: ImageHandle,
                level: u32,
                bytes: &[u8],
            ) -> Result<(), RhiError> {
                <$t>::upload_image(self, handle, level, bytes)
            }
            fn register_texture(&mut self, handle: ImageHandle) -> Result<TextureIndex, RhiError> {
                <$t>::register_texture(self, handle)
            }
            fn create_pipeline(
                &mut self,
                desc: &PipelineDesc<'_>,
            ) -> Result<PipelineHandle, RhiError> {
                <$t>::create_pipeline(self, desc)
            }
            fn destroy_pipeline(&mut self, handle: PipelineHandle) -> Result<(), RhiError> {
                <$t>::destroy_pipeline(self, handle)
            }
            fn destroy_buffer(&mut self, handle: BufferHandle) -> Result<(), RhiError> {
                <$t>::destroy_buffer(self, handle)
            }
            fn destroy_image(&mut self, handle: ImageHandle) -> Result<(), RhiError> {
                <$t>::destroy_image(self, handle)
            }
        }
    };
}

pass_host!(Rhi);
pass_host!(gg_rhi::OffscreenRhi);

impl BoxPass {
    /// Upload the box and build the pipelines. One flush, at startup.
    fn new(rhi: &mut impl GpuHost) -> Result<Self, RhiError> {
        let (vertices, indices) = unit_box();
        let vertex_bytes = bytemuck::cast_slice(&vertices);
        let index_bytes = bytemuck::cast_slice(&indices);

        let vertex_buffer = rhi.create_buffer(&BufferDesc {
            name: "render.box.vertices",
            size: vertex_bytes.len() as u64,
            kind: BufferKind::Storage,
        })?;
        let index_buffer = rhi.create_buffer(&BufferDesc {
            name: "render.box.indices",
            size: index_bytes.len() as u64,
            kind: BufferKind::Index,
        })?;
        rhi.upload_buffer(vertex_buffer, 0, vertex_bytes)?;
        rhi.upload_buffer(index_buffer, 0, index_bytes)?;
        rhi.flush_uploads()?;

        Ok(BoxPass {
            prepass: rhi.create_pipeline(&prepass_desc())?,
            forward: rhi.create_pipeline(&forward_desc())?,
            post: rhi.create_pipeline(&post_desc())?,
            vertices: vertex_buffer,
            indices: index_buffer,
            vertex_address: rhi.buffer_address(vertex_buffer)?,
            index_count: indices.len() as u32,
            pushes: Vec::new(),
        })
    }

    /// Rebuild this frame's push constants.
    fn build(&mut self, extent: (u32, u32), extracted: &Extracted, view: &View) {
        let view_projection = view.view_projection(extent);
        let address = self.vertex_address;
        self.pushes.clear();
        self.pushes.extend(
            extracted
                .instances
                .iter()
                .map(|instance| push_for(address, view_projection, instance)),
        );
    }

    /// The frame's boxes, drawn by `pipeline`.
    ///
    /// A draw call per box, which is the honest cost while the Ugly Game draws
    /// a few hundred; instancing is a §4.6 vertex-format question rather than a
    /// graph one, and it belongs with real meshes.
    fn draws(&self, pipeline: PipelineHandle) -> Vec<DrawSpec<'_>> {
        self.pushes
            .iter()
            .map(|push| DrawSpec {
                pipeline,
                push_constants: bytemuck::bytes_of(push),
                count: self.index_count,
                index_buffer: Some(self.indices),
            })
            .collect()
    }

    /// Where the post pass reads the scene attachment from.
    fn post_push(
        &self,
        frame: &graph::Frame<'_>,
        scene: graph::ResourceId,
    ) -> Result<post_shader::PostPush, RhiError> {
        let index = frame.texture(scene).ok_or_else(|| {
            RhiError::Loader("the scene attachment has no bindless slot to sample".into())
        })?;
        Ok(post_shader::PostPush::new(
            index.get(),
            Sampler::NearestClamp.index(),
        ))
    }

    fn post_draw<'a>(&self, push: &'a post_shader::PostPush) -> DrawSpec<'a> {
        DrawSpec {
            pipeline: self.post,
            push_constants: bytemuck::bytes_of(push),
            count: FULLSCREEN_VERTICES,
            index_buffer: None,
        }
    }

    /// Release the pipelines and both buffers.
    fn destroy(self, rhi: &mut impl GpuHost) -> Result<(), RhiError> {
        rhi.destroy_pipeline(self.prepass)?;
        rhi.destroy_pipeline(self.forward)?;
        rhi.destroy_pipeline(self.post)?;
        rhi.destroy_buffer(self.vertices)?;
        rhi.destroy_buffer(self.indices)
    }
}

/// The UI layer over a resolved frame: alpha-blended, depth-free, keeping what
/// is already there. Declared as a pass rather than appended to the post pass's
/// draws because it targets a different pipeline state, and because M13's
/// `gg-ui` gets a pass of its own in the graph either way (§4.9).
pub fn ui_pass<'a>(backbuffer: graph::ResourceId, draws: &'a [DrawSpec<'a>]) -> Declared<'a> {
    Declared {
        name: "ui",
        body: Body::Draw {
            color: Some((backbuffer, Load::Keep)),
            depth: None,
            // The coverage atlas is an uploaded texture like any material's,
            // already in a sampled layout — not a graph resource, so there is
            // no transition for the graph to derive.
            samples: &[],
            draws,
        },
    }
}

/// The §4.5 v1 scene graph: depth prepass → forward opaque → fullscreen post.
///
/// A free function rather than a method because it is the *shape*, and the
/// shape is what a second caller wants — the golden harness declares these
/// three and appends a readback pass (§4.10), and a shape it had to restate
/// would be a shape that could disagree with the screen's.
#[expect(clippy::too_many_arguments, reason = "one frame's declarations")]
pub fn scene_graph<'a>(
    backbuffer: graph::ResourceId,
    scene: graph::ResourceId,
    depth: graph::ResourceId,
    clear: [f32; 4],
    prepass_draws: &'a [DrawSpec<'a>],
    forward_draws: &'a [DrawSpec<'a>],
    post_draws: &'a [DrawSpec<'a>],
    samples: &'a [graph::ResourceId],
) -> [Declared<'a>; 3] {
    [
        Declared {
            name: "depth-prepass",
            body: Body::Draw {
                color: None,
                depth: Some((depth, DepthUse::WriteStore)),
                samples: &[],
                draws: prepass_draws,
            },
        },
        Declared {
            name: "forward-opaque",
            body: Body::Draw {
                color: Some((scene, Load::Clear(clear))),
                depth: Some((depth, DepthUse::Test)),
                samples: &[],
                draws: forward_draws,
            },
        },
        Declared {
            name: "post",
            // `Keep`, not a clear: the pass writes every pixel of the target
            // from a fullscreen triangle, so clearing first would be a full
            // target's worth of writes thrown away.
            body: Body::Draw {
                color: Some((backbuffer, Load::Keep)),
                depth: None,
                samples,
                draws: post_draws,
            },
        },
    ]
}

/// The depth prepass: position only, no colour, depth stored for the forward
/// pass to test against.
fn prepass_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "ugly.prepass",
        vs_spirv: shader::VS_DEPTH_SPIRV,
        vs_entry: shader::VS_DEPTH_ENTRY,
        fs_spirv: shader::FS_DEPTH_SPIRV,
        fs_entry: shader::FS_DEPTH_ENTRY,
        push_constant_size: core::mem::size_of::<shader::UglyPush>() as u32,
        color: ColorTarget::None,
        blend: Blend::Off,
        depth: DepthMode::Write,
    }
}

/// The forward pass, into the scene attachment rather than the backbuffer: the
/// post pass is what reaches the screen. Depth is tested, not written — the
/// prepass placed every fragment already, and reverse-Z's `GREATER_OR_EQUAL`
/// lets the same geometry re-draw exactly where it landed.
fn forward_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "ugly.forward",
        vs_spirv: shader::VS_MAIN_SPIRV,
        vs_entry: shader::VS_MAIN_ENTRY,
        fs_spirv: shader::FS_MAIN_SPIRV,
        fs_entry: shader::FS_MAIN_ENTRY,
        push_constant_size: core::mem::size_of::<shader::UglyPush>() as u32,
        color: ColorTarget::Format(SCENE_FORMAT),
        blend: Blend::Off,
        depth: DepthMode::TestOnly,
    }
}

/// The fullscreen post pass, onto whatever the frame lands in.
fn post_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "post",
        vs_spirv: post_shader::VS_MAIN_SPIRV,
        vs_entry: post_shader::VS_MAIN_ENTRY,
        fs_spirv: post_shader::FS_MAIN_SPIRV,
        fs_entry: post_shader::FS_MAIN_ENTRY,
        push_constant_size: core::mem::size_of::<post_shader::PostPush>() as u32,
        color: ColorTarget::Backbuffer,
        blend: Blend::Off,
        depth: DepthMode::Off,
    }
}

/// The graph's scene attachment format. sRGB, like the swapchain: the post pass
/// samples it (decoding) and writes an sRGB target (encoding), so the resolve
/// is an identity up to 8-bit rounding.
const SCENE_FORMAT: ImageFormat = ImageFormat::Rgba8Srgb;

/// The fullscreen triangle the post pass draws — three shader-generated
/// vertices, no buffer.
const FULLSCREEN_VERTICES: u32 = 3;

/// Push constants for one instance.
fn push_for(
    vertices: DeviceAddress,
    view_projection: render::Mat4,
    instance: &Instance,
) -> shader::UglyPush {
    let model = render::Mat4::from_scale_rotation_translation(
        instance.half_extent,
        instance.rotation,
        instance.offset,
    );
    shader::UglyPush::new(
        render::rows(view_projection * model),
        vertices,
        srgb_to_linear(instance.color),
        instance.rotation.to_array(),
    )
}

/// `0x00RRGGBB` → linear rgb, with alpha unused.
///
/// The swapchain target encodes sRGB, so a colour handed over as sRGB bytes has
/// to be linearized here or every tint comes out washed. Gamma 2.0 — squaring —
/// rather than 2.2 or the piecewise curve: `powf` is banned engine-wide (§3, and
/// it would want `gg_math::sim` in a crate downstream of the membrane), this is
/// a tint on an untextured box, and the exact transfer function is `ggc`'s
/// problem at import (§4.6).
fn srgb_to_linear(color: u32) -> [f32; 4] {
    let channel = |shift: u32| {
        let byte = ((color >> shift) & 0xff) as f32 / 255.0;
        byte * byte
    };
    [channel(16), channel(8), channel(0), 1.0]
}

/// A box of half-extent 1 — the instance's scale is what gives it a size. 24
/// vertices so every face carries its own normal, 36 indices.
fn unit_box() -> (Vec<Vertex>, Vec<u32>) {
    // (normal, u axis, v axis) per face, u x v pointing outward.
    const FACES: [([f32; 3], [f32; 3], [f32; 3]); 6] = [
        ([1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]),
        ([-1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]),
        ([0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, -1.0]),
        ([0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]),
        ([0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
        ([0.0, 0.0, -1.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
    ];
    const CORNERS: [(f32, f32); 4] = [(-1.0, -1.0), (1.0, -1.0), (1.0, 1.0), (-1.0, 1.0)];

    let mut vertices = Vec::with_capacity(24);
    let mut indices = Vec::with_capacity(36);
    for (normal, u_axis, v_axis) in FACES {
        let base = vertices.len() as u32;
        for (u, v) in CORNERS {
            vertices.push(Vertex {
                position: [
                    normal[0] + u * u_axis[0] + v * v_axis[0],
                    normal[1] + u * u_axis[1] + v * v_axis[1],
                    normal[2] + u * u_axis[2] + v * v_axis[2],
                ],
                normal,
            });
        }
        indices.extend_from_slice(&[base, base + 1, base + 2, base, base + 2, base + 3]);
    }
    (vertices, indices)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn the_box_is_closed_and_its_normals_point_outward() {
        let (vertices, indices) = unit_box();
        assert_eq!(vertices.len(), 24);
        assert_eq!(indices.len(), 36);
        for v in &vertices {
            for axis in v.position {
                assert!(
                    (axis.abs() - 1.0).abs() < 1e-6,
                    "corner at {:?}",
                    v.position
                );
            }
            let dot = v.position[0] * v.normal[0]
                + v.position[1] * v.normal[1]
                + v.position[2] * v.normal[2];
            assert!(dot > 0.0, "normal {:?} faces inward", v.normal);
        }
    }

    #[test]
    fn the_near_plane_maps_to_one_and_the_far_distance_to_zero() {
        // Reverse-Z, the §2-locked convention, checked where a projection is
        // actually built rather than only where it is defined: a matrix assembled
        // the ordinary way renders a scene that is subtly, consistently wrong.
        let view = View::default();
        let clip = view.view_projection((640, 360));
        let near = clip * render::Vec4::new(0.0, 0.0, -view.near, 1.0);
        let far = clip * render::Vec4::new(0.0, 0.0, -1.0e9, 1.0);
        assert!((near.z / near.w - 1.0).abs() < 1e-5, "near maps to 1");
        assert!((far.z / far.w).abs() < 1e-5, "the far distance maps to 0");
    }

    #[test]
    fn a_yawed_view_looks_where_the_yaw_says() {
        let view = View {
            yaw: core::f32::consts::FRAC_PI_2,
            ..View::default()
        };
        // +90° of yaw about +Y turns the -Z forward axis onto -X.
        let forward = view.rotation() * render::Vec3::NEG_Z;
        assert!(
            (forward - render::Vec3::NEG_X).length() < 1e-6,
            "{forward:?}"
        );
    }

    /// The whole path with no window in it, through the whole graph: a game
    /// component, extract's narrowing, the push constants, a depth prepass, the
    /// forward pass over its result, the fullscreen resolve, and pixels back
    /// through §4.5's readback pass (§1.5 — the only rendering an automated tier
    /// is allowed to do).
    ///
    /// This is the v1 pass list end to end. The shell runs the same four minus
    /// the readback, and the shell is windowed and therefore manual — so this is
    /// where the derived barriers between prepass, forward and post are proven.
    #[test]
    fn the_v1_pass_list_puts_a_declared_box_on_the_target() {
        use gg_ecs::World;
        use gg_ecs::boundary::Renderable;
        use gg_math::sim;

        const EXTENT: (u32, u32) = (64, 64);
        let mut world = World::new();
        world.register::<Renderable>().unwrap();
        let entity = world.spawn();
        world
            .insert(
                entity,
                // Dead ahead of an unrotated eye, big enough to cover the middle
                // and small enough to leave the corners clear.
                Renderable::boxed(
                    sim::DVec3::new(0.0, 0.0, -4.0),
                    sim::Vec3::splat(1.0),
                    0x00ff_0000,
                ),
            )
            .unwrap();
        let mut extracted = Extracted::default();
        extracted
            .transforms::<Renderable>(&world, sim::DVec3::ZERO)
            .unwrap();

        // Through the public offscreen entry point, not around it: this is the
        // path gg-golden gates on, and a test that assembled the same passes
        // beside it would prove them about itself.
        let mut renderer = OffscreenRenderer::new(EXTENT).unwrap();
        let frame = renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();

        // Every pass the graph derived is a pass the RHI was handed, in the
        // order the dump prints — §6 M6's "matches the executed order", as a
        // machine rather than as a claim about a text file. `order` is read off
        // the executed list, so this is the submission itself.
        assert_eq!(
            frame.order,
            [
                "depth-prepass",
                "forward-opaque",
                "post",
                "readback",
                "frame-end"
            ]
        );
        for name in &frame.order {
            assert!(
                frame.dump.contains(name.as_str()),
                "the dump names every executed pass: {name}"
            );
        }

        let at = |x: u32, y: u32| {
            let i = ((y * EXTENT.0 + x) * 4) as usize;
            [frame.pixels[i], frame.pixels[i + 1], frame.pixels[i + 2]]
        };
        let middle = at(EXTENT.0 / 2, EXTENT.1 / 2);
        assert!(
            middle[0] > 0x40,
            "the box is there and it is red: {middle:?}"
        );
        assert_eq!((middle[1], middle[2]), (0, 0), "and only red");
        assert_eq!(at(0, 0), [0, 0, 0], "the corners are still the clear");

        assert!(
            renderer.shutdown().clean(),
            "no leaks, no validation messages"
        );
    }

    #[test]
    fn colours_arrive_as_the_game_wrote_them() {
        assert_eq!(srgb_to_linear(0x0000_0000), [0.0, 0.0, 0.0, 1.0]);
        assert_eq!(srgb_to_linear(0x00ff_ffff), [1.0, 1.0, 1.0, 1.0]);
        // Channel order, which is the one thing a swap here would silently
        // survive: pure red stays in the first slot.
        let red = srgb_to_linear(0x00ff_0000);
        assert_eq!((red[0], red[1], red[2]), (1.0, 0.0, 0.0));
    }
}
