//! `gg-render` (§4.5) — the render graph, and the passes over it.
//!
//! The graph is [`graph`]: passes declare virtual resources and usages, and
//! every `synchronization2` barrier and layout transition in a frame is derived
//! from those declarations rather than written by hand. That derivation's
//! Vulkan half lives behind the §3 seam in `gg-rhi`; this side names no stage,
//! no access mask and no layout.
//!
//! [`Renderer`] is the graph put to work for the shell: depth prepass → forward
//! opaque → fullscreen post → present, the §4.5 v1 list minus the readback pass,
//! which is a harness's business rather than a window's. The three calls the
//! shell makes ([`Renderer::new`], [`Renderer::frame`], [`Renderer::shutdown`])
//! are the same three it made at M5 — that was the part meant to survive.
//!
//! It draws exactly one primitive — a box — because the game says where, how big
//! and what colour, and nothing else (`gg_ecs::boundary::Renderable`). A
//! renderer with more opinions than that would be a renderer the Ugly Game
//! cannot restyle without rebuilding the engine, which is the wrong half of the
//! cooperative loop to make expensive.

#![deny(missing_docs)]

pub mod content;
pub mod cvars;
pub mod graph;
mod lighting;
/// The overlay's luminance histogram (§6 M11).
pub mod luminance;
// Private, and the §5.10 review at M12 is why: nothing outside this crate reaches
// either, and both are large — 48 items of upload scheduling and 79 of generated
// push-constant layout. A public `shaders_gen` would make every shader edit an
// API event, which is exactly backwards: the generated structs are how this crate
// talks to its own SPIR-V, not a contract it offers.
mod residency;
mod scene;
pub mod ui;

/// Generated by `cargo xtask shaders` from `shaders/*.slang` (§4.4).
mod shaders_gen {
    /// The fullscreen post pass.
    pub mod post;
    /// The pack pass: mesh geometry and a base-colour map (§4.6).
    pub mod scene;
    /// The forward pass and the depth prepass: push constants + embedded SPIR-V.
    pub mod ugly;
    /// The UI layer's one pipeline.
    pub mod ui;
}

use std::path::Path;

use content::{Content, ContentError};
use gg_assets::AssetId;
use gg_extract::{Extracted, Frustum, Instance, Scenes};
use gg_math::render;
pub use gg_rhi::Viewport;
use gg_rhi::{
    Blend, BufferDesc, BufferHandle, BufferKind, ColorTarget, DepthMode, DeviceAddress,
    DeviceReport, DrawSpec, FrameOutcome, FrameStart, GpuClock, GraphContext, ImageDesc,
    ImageFormat, ImageHandle, MemoryUse, PassTiming, PipelineDesc, PipelineHandle, Rhi, RhiError,
    Sampler, ShutdownReport, TextureIndex,
};
use graph::{Body, Declared, DepthUse, Load, Transients};
use raw_window_handle::{HasDisplayHandle, HasWindowHandle};
use scene::ScenePass;
use shaders_gen::post as post_shader;
use shaders_gen::ugly as shader;

/// One vertex, mirroring `ugly.slang`'s `VERTEX_STRIDE` byte layout. The shader
/// reads these at hardcoded offsets through a device address, so the layout is
/// frozen below rather than trusted.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct Vertex {
    position: [f32; 3],
    normal: [f32; 3],
}

const _: () = {
    assert!(core::mem::size_of::<Vertex>() == 24);
    assert!(core::mem::offset_of!(Vertex, normal) == 12);
};

/// Where the frame is seen from, on the render side of the membrane.
///
/// Position is absent on purpose: it never crosses. [`Extracted`] arrives
/// already camera-relative, so the eye *is* the origin here and the view matrix
/// carries rotation only — which is what makes a camera 10^12 m out render
/// without jitter (§1.4, §4.2.1).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct View {
    /// Rotation about +Y, radians.
    pub yaw: f32,
    /// Rotation about the camera's right axis, radians.
    pub pitch: f32,
    /// Vertical field of view, radians.
    pub fov_y: f32,
    /// Near plane. With reverse-Z and an infinite far plane this is the *only*
    /// depth-precision knob there is (§2, Math row).
    pub near: f32,
}

impl Default for View {
    /// Not a constant: `fov_y` and `near` are CVars (§4.8), so *rebuilding* a
    /// `View` each frame is how a console edit reaches the screen — and a caller
    /// that keeps one instead has pinned them, deliberately.
    fn default() -> Self {
        View {
            yaw: 0.0,
            pitch: 0.0,
            fov_y: cvars::FOV.float() as f32,
            near: cvars::NEAR.float() as f32,
        }
    }
}

impl View {
    fn rotation(&self) -> render::Quat {
        // YXZ: yaw about world +Y first, then pitch about the rotated right
        // axis — the fly-camera order, and the one that never rolls.
        render::Quat::from_euler(render::EulerRot::YXZ, self.yaw, self.pitch, 0.0)
    }

    /// This view's culling frustum, for the extract stage.
    ///
    /// Built here rather than in `gg-extract` because the projection convention
    /// is this crate's (§2, Math row) and a second construction of it is a
    /// second thing to get subtly wrong. The shell hands the result across,
    /// which is the whole of its part in culling.
    #[must_use]
    pub fn frustum(&self, extent: (u32, u32)) -> Frustum {
        Frustum::from_view_projection(self.view_projection(extent))
    }

    /// Camera-relative world → clip.
    fn view_projection(&self, extent: (u32, u32)) -> render::Mat4 {
        let rotation = self.rotation();
        let aspect = extent.0.max(1) as f32 / extent.1.max(1) as f32;
        let view = render::camera::rh::view::look_to_mat4(
            render::Vec3::ZERO,
            rotation * render::Vec3::NEG_Z,
            rotation * render::Vec3::Y,
        );
        render::perspective_reverse_z(self.fov_y, aspect, self.near) * view
    }
}

/// A window's GPU state and the passes over it — what the shell holds.
///
/// It owns the [`Rhi`] rather than taking one per call so the shell never names
/// `gg-rhi` at all: §3 caps the shell at zero engine logic, and a host that
/// creates pipelines is past that line whatever the line count says.
pub struct Renderer {
    rhi: Rhi,
    pass: BoxPass,
    scene: ScenePass,
    ui: ui::UiPass,
    lighting: lighting::Lighting,
    luminance: luminance::Luminance,
    transients: Transients,
    /// The pack, once a host has named one. `None` is a renderer that draws
    /// boxes and nothing else — which is every tier before M9 and every run
    /// without `--pack`.
    content: Option<Content>,
    /// Where the frame lands in the window. See [`Renderer::set_viewport`].
    viewport: Option<Viewport>,
}

impl Renderer {
    /// Bring up the device and swapchain for `window`, and upload the pass.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses: no device, no surface, or a failed upload.
    ///
    /// # Safety of teardown
    ///
    /// The surface may not outlive the window it came from, so [`Renderer::shutdown`]
    /// must run while the window is still alive (§4.3).
    pub fn new(
        window: &(impl HasWindowHandle + HasDisplayHandle),
        extent: (u32, u32),
    ) -> Result<Self, RhiError> {
        let mut rhi = Rhi::new(window, extent)?;
        let pass = BoxPass::new(&mut rhi)?;
        let scene = ScenePass::new(&mut rhi)?;
        let ui = ui::UiPass::new(&mut rhi)?;
        let lighting = lighting::Lighting::new(&mut rhi)?;
        let luminance = luminance::Luminance::new(&mut rhi)?;
        Ok(Renderer {
            rhi,
            pass,
            scene,
            ui,
            lighting,
            luminance,
            transients: Transients::default(),
            content: None,
            viewport: None,
        })
    }

    /// Map a pack and start its load clock (§4.6). The game names what to draw
    /// out of it; this only says which file.
    ///
    /// # Errors
    /// A file that will not open, or a pack the loader refuses by name.
    pub fn open_pack(&mut self, path: &Path) -> Result<(), ContentError> {
        self.content = Some(Content::open(path)?);
        Ok(())
    }

    /// Instances staged and draws issued by the pack pass last frame (§6 M10).
    ///
    /// Public because "ten thousand objects, four draws" is an exit claim, and a
    /// claim a harness cannot count is a claim nobody checks — `gg-golden`'s
    /// `field` scene asserts on this.
    #[must_use]
    pub fn draw_counts(&self) -> (usize, usize) {
        self.scene.counts()
    }

    /// This frame's luminance histogram, or `None` when `r.histogram` is off
    /// (§6 M11's exit row). Bins are log2 luminance, darkest first.
    ///
    /// Two frames behind on a window and current offscreen — see
    /// [`luminance`](crate::luminance) for why, which is the same reason the
    /// per-pass GPU times beside it are.
    #[must_use]
    pub fn luminance(&self) -> Option<&[u32; luminance::BINS]> {
        self.luminance.bins()
    }

    /// The pack, for a host reporting on its load (§6 M9's exit row).
    #[must_use]
    pub fn pack(&self) -> Option<&Content> {
        self.content.as_ref()
    }

    /// Re-open the pack now if it has been rewritten, rather than waiting for
    /// the frame that would notice (§4.6). `true` if it had been.
    ///
    /// # Errors
    /// A rewritten pack the loader refuses — leaving the old one playing.
    pub fn reload_pack(&mut self) -> Result<bool, ContentError> {
        match &mut self.content {
            Some(content) => content.poll_reload(&mut self.rhi),
            None => Ok(false),
        }
    }

    /// What [`gg_extract::Extracted::append_models`] expands scene assets
    /// through. A renderer with no pack expands nothing, so a host calls this
    /// unconditionally.
    #[must_use]
    pub fn scenes(&self) -> &dyn Scenes {
        match &self.content {
            Some(content) => content,
            None => &(),
        }
    }

    /// Hand the UI pass the coverage atlas its glyphs are cut from (§4.9).
    /// Called once, by whoever owns the font — this side never learns what a
    /// glyph is. Until it is called the UI pass draws nothing.
    ///
    /// # Errors
    ///
    /// A bitmap whose length disagrees with its extent, or an allocation.
    pub fn set_ui_atlas(&mut self, coverage: &ui::Coverage<'_>) -> Result<(), RhiError> {
        self.ui.set_atlas(&mut self.rhi, coverage)
    }

    /// Live buffer and image allocations — the overlay's memory row (§4.8).
    pub fn memory(&self) -> MemoryUse {
        self.rhi.memory()
    }

    /// Which device was chosen, and what it can do (§4.3).
    pub fn device(&self) -> &DeviceReport {
        self.rhi.device_report()
    }

    /// The surface the next frame will present, in physical pixels — the whole
    /// window. What the *game* is composed for is [`Renderer::view_extent`],
    /// which is smaller whenever a viewport is set.
    pub fn extent(&self) -> (u32, u32) {
        self.rhi.swapchain_extent()
    }

    /// Put the game inside `viewport` instead of over the whole window, in
    /// physical pixels from the top-left; `None` restores the whole window.
    ///
    /// This is a **render target and not a crop**: the scene and depth
    /// attachments are allocated at the viewport's size and the projection is
    /// built from its aspect, so an object at the edge of the viewport is at the
    /// edge of the picture. A host that instead let the frame cover the window
    /// and drew panels over it — which is what M15 shipped — is showing the
    /// middle of a frame composed for a wider rectangle, and leaves the
    /// letterbox `gg_ui::Fit` opens at any non-16:9 window showing bare game.
    ///
    /// Sticky, like the pack and the atlas: a shell sets it when the editor
    /// opens and clears it when the editor closes, rather than restating it
    /// every frame. Kept in physical pixels because that is what a scissor is
    /// in — converting canvas units is the caller's, and `gg_editor::viewport`
    /// is where that arithmetic lives.
    pub fn set_viewport(&mut self, viewport: Option<Viewport>) {
        self.viewport = viewport;
    }

    /// The extent the next frame's projection will be built from: the viewport's
    /// when one is set, the surface's otherwise.
    ///
    /// A shell culling against [`View::frustum`] must pass *this*, not
    /// [`Renderer::extent`] — a frustum built from the window while the picture
    /// is composed for a narrower rectangle culls objects that are on screen.
    pub fn view_extent(&self) -> (u32, u32) {
        view_extent(self.viewport, self.rhi.swapchain_extent())
    }

    /// New window size in physical pixels. `(0, 0)` suspends rather than
    /// recreates.
    ///
    /// A viewport set against the old size survives: it is clamped to the
    /// attachment when the frame records (`gg_rhi::Viewport::clamped`), and the
    /// host restates it from the new extent on the tick that follows.
    pub fn resize(&mut self, width: u32, height: u32) {
        self.rhi.resize(width, height);
    }

    /// Per-pass GPU milliseconds from the last retired frame (§4.8) — the rows
    /// the debug overlay draws. Empty in a build without the timestamps, or
    /// before the first frame comes back.
    pub fn pass_timings(&self) -> &[PassTiming] {
        self.rhi.pass_timings()
    }

    /// The device clock, for a profiler anchoring GPU spans to CPU time (§4.8).
    pub fn gpu_clock(&self) -> Option<GpuClock> {
        self.rhi.gpu_clock()
    }

    /// One frame through the graph: depth prepass, forward opaque, post, the UI
    /// layer over it, present.
    ///
    /// `ui` is this frame's whole UI layer as one batch (§4.9) — empty means no
    /// UI pass is declared at all, which is what a dist build with no overlay
    /// hands over every frame.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses while compiling, recording, submitting or
    /// presenting.
    pub fn frame(
        &mut self,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
        ui: &[ui::UiVertex],
    ) -> Result<FrameOutcome, RhiError> {
        /// Attempts before a frame gives up and leaves the surface to the next
        /// one. Three, because each costs a recreate and the operator's drag is
        /// still moving underneath it — spinning would stall the resize instead
        /// of tracking it.
        const ATTEMPTS: u32 = 3;

        // Before `begin_frame`, not inside it: uploads go to the transfer queue
        // through the staging ring and belong to no frame slot (§4.3). Above the
        // retry as well, so a second attempt re-acquires without re-streaming.
        stream(&mut self.content, &mut self.rhi, extracted)?;
        // An out-of-date acquire is ordinary while a window is being dragged:
        // the surface moves faster than a frame can be built. Retried *here*
        // rather than left to the next frame, because during a Win32 modal
        // resize loop there is no next frame until the operator lets go — a
        // skipped frame is then a window that shows nothing new for the whole
        // drag, which is what the black band trailing the border was (§6 M15.1).
        let mut outcome = FrameOutcome::SkippedOutOfDate;
        for _ in 0..ATTEMPTS {
            outcome = self.frame_once(extracted, view, color, ui)?;
            if !matches!(outcome, FrameOutcome::SkippedOutOfDate) {
                break;
            }
        }
        Ok(outcome)
    }

    /// One attempt at [`Renderer::frame`]: recreate if due, compile, record,
    /// submit, present. Split out so the retry above re-enters `begin_frame`,
    /// which is the only place the swapchain is rebuilt.
    fn frame_once(
        &mut self,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
        ui: &[ui::UiVertex],
    ) -> Result<FrameOutcome, RhiError> {
        let token = match self.rhi.begin_frame()? {
            FrameStart::Ready(token) => token,
            FrameStart::Skipped(outcome) => return Ok(outcome),
        };
        let extent = token.extent();
        // After `begin_frame`, which is where this slot's previous frame is
        // waited out — the wait that makes writing its region safe. Every pass
        // that stages into a per-slot region has to be on this side of it.
        let slot = GraphContext::frame_slot(&self.rhi);
        // Right after that wait, which is the only synchronization the readback
        // needs: this slot's previous frame has retired, so its luminance grid is
        // on the host side of the copy (§6 M11). Two frames old, exactly like the
        // per-pass GPU times the same panel draws.
        let histogram = luminance::Luminance::enabled();
        match histogram {
            true => self.luminance.read(&self.rhi, slot)?,
            false => self.luminance.clear(),
        }
        // Known before the graph exists, which is what lets the draws carry it:
        // the shadow map's bindless index does not exist until the graph has
        // acquired it, and acquiring it holds the borrow the write would need.
        let frame_address = self.lighting.slot_address(slot);
        // Everything the game is composed for is this, not the window: the
        // projection, the culling frustum the shell already built from
        // `view_extent`, and both attachments below. The window's own extent is
        // left to the two things that really are the window's — the UI layer,
        // and where the post pass puts the result.
        let view_extent = view_extent(self.viewport, extent);
        // After `view_extent`, because a cascade is fitted to the frustum the
        // game is composed for and the window's aspect is not that frustum.
        let sun = self.lighting.plan(extracted, view, view_extent);
        let cascades = sun.map_or(0, |s| s.cascades().len());
        self.pass.build(extracted, frame_address);
        self.pass
            .build_shadow(extracted, frame_address, sun.as_ref());
        let content = self.content.as_ref();
        self.scene.build(
            &mut self.rhi,
            slot,
            view_extent,
            extracted,
            view,
            content,
            frame_address,
            cascades,
        )?;
        report_draws(&self.scene, extracted);
        self.ui.write(&mut self.rhi, slot, ui)?;
        let ui_push = self.ui.push(extent);

        let mut frame = self.transients.frame(&mut self.rhi, extent)?;
        let backbuffer = frame.backbuffer();
        let scene = frame.color_at("scene.color", view_extent, SCENE_FORMAT)?;
        let depth = frame.depth_at("scene.depth", view_extent)?;
        let shadows = shadow_maps(&mut frame, sun)?;
        let shadow_textures: Vec<TextureIndex> =
            shadows.iter().filter_map(|id| frame.texture(*id)).collect();
        let grid = histogram
            .then(|| frame.color_at("luminance.grid", luminance::GRID, SCENE_FORMAT))
            .transpose()?;
        let post_push = self.pass.post_push(&frame, scene)?;

        let prepass_draws = prepass_draws(&self.pass, &self.scene);
        let shadow_draws: Vec<Vec<DrawSpec<'_>>> = (0..shadows.len())
            .map(|cascade| shadow_draws(&self.pass, &self.scene, cascade))
            .collect();
        let shadow_slices: Vec<&[DrawSpec<'_>]> = shadow_draws.iter().map(Vec::as_slice).collect();
        let forward_draws = forward_draws(&self.pass, &self.scene);
        let post_draws = [self.pass.post_draw(&post_push)];
        let samples = [scene];
        let forward_samples: Vec<graph::ResourceId> = shadows.clone();
        let mut declared = scene_graph(&SceneFrame {
            backbuffer,
            scene,
            depth,
            shadows: &shadows,
            clear: color,
            viewport: self.viewport,
            prepass_draws: &prepass_draws,
            shadow_draws: &shadow_slices,
            forward_draws: &forward_draws,
            post_draws: &post_draws,
            samples: &samples,
            forward_samples: &forward_samples,
        });
        let ui_draws: Vec<DrawSpec<'_>> = self.ui.draw(&ui_push).into_iter().collect();
        if !ui_draws.is_empty() {
            declared.push(ui_pass(backbuffer, &ui_draws));
        }
        let downsample_draws = [self.pass.downsample_draw(&post_push)];
        if let Some(grid) = grid {
            let into = frame.readback_buffer("render.luminance", self.luminance.buffer(slot));
            declared.extend(luminance_passes(grid, into, &samples, &downsample_draws));
            self.luminance.mark(slot);
        }
        let compiled = frame.compile(&declared)?;
        // After `compile`, which is where the graph hands the RHI back — and
        // before `execute`, which is the only thing that lets the GPU see it.
        self.lighting.write(
            &mut self.rhi,
            slot,
            view.view_projection(view_extent),
            &extracted.lights,
            &shadow_textures,
        )?;
        self.rhi.execute(token, &compiled.passes())
    }

    /// The graph the next frame will run, as text — `--dump-render-graph`
    /// (§4.5). Compiling it is what the frame does anyway, so what this prints
    /// is what runs.
    ///
    /// # Errors
    ///
    /// Whatever compiling the graph refuses.
    pub fn dump_graph(&mut self) -> Result<String, RhiError> {
        let extent = self.rhi.swapchain_extent();
        // The sun as the *last* frame planned it, like the UI pass below: what
        // the next frame's lights will be is not knowable here.
        let sun = self.lighting.sun();
        let view_extent = view_extent(self.viewport, extent);
        let mut frame = self.transients.frame(&mut self.rhi, extent)?;
        let backbuffer = frame.backbuffer();
        let scene = frame.color_at("scene.color", view_extent, SCENE_FORMAT)?;
        let depth = frame.depth_at("scene.depth", view_extent)?;
        let shadows = shadow_maps(&mut frame, sun)?;
        let post_push = self.pass.post_push(&frame, scene)?;
        let prepass_draws = prepass_draws(&self.pass, &self.scene);
        let shadow_draws: Vec<Vec<DrawSpec<'_>>> = (0..shadows.len())
            .map(|cascade| shadow_draws(&self.pass, &self.scene, cascade))
            .collect();
        let shadow_slices: Vec<&[DrawSpec<'_>]> = shadow_draws.iter().map(Vec::as_slice).collect();
        let forward_draws = forward_draws(&self.pass, &self.scene);
        let post_draws = [self.pass.post_draw(&post_push)];
        let samples = [scene];
        let forward_samples: Vec<graph::ResourceId> = shadows.clone();
        let mut declared = scene_graph(&SceneFrame {
            backbuffer,
            scene,
            depth,
            shadows: &shadows,
            clear: [0.0; 4],
            viewport: self.viewport,
            prepass_draws: &prepass_draws,
            shadow_draws: &shadow_slices,
            forward_draws: &forward_draws,
            post_draws: &post_draws,
            samples: &samples,
            forward_samples: &forward_samples,
        });
        // The UI pass as the *last* frame declared it: what the next one draws
        // is not knowable here, and a dump that always omitted it would print a
        // graph the screen never runs.
        let ui_push = self.ui.push(extent);
        let ui_draws: Vec<DrawSpec<'_>> = self.ui.draw(&ui_push).into_iter().collect();
        if !ui_draws.is_empty() {
            declared.push(ui_pass(backbuffer, &ui_draws));
        }
        Ok(frame.compile(&declared)?.dump())
    }

    /// Release everything and account for it (§4.3, §5.4).
    pub fn shutdown(mut self) -> ShutdownReport {
        // A refusal here can only be a handle this struct did not issue, which
        // cannot happen — and if it somehow did, the unreleased memory shows up
        // in the report below, which is the check that actually matters.
        drop(self.transients.destroy(&mut self.rhi));
        if let Some(content) = &mut self.content {
            drop(content.destroy(&mut self.rhi));
        }
        drop(self.pass.destroy(&mut self.rhi));
        drop(self.scene.destroy(&mut self.rhi));
        drop(self.ui.destroy(&mut self.rhi));
        drop(self.lighting.destroy(&mut self.rhi));
        drop(self.luminance.destroy(&mut self.rhi));
        self.rhi.shutdown()
    }
}

/// One offscreen frame: the pixels, and the graph that produced them.
pub struct OffscreenFrame {
    /// RGBA8, tightly packed, `extent.0 * extent.1 * 4` bytes.
    pub pixels: Vec<u8>,
    /// The compiled graph as text (§4.5).
    pub dump: String,
    /// The passes handed to the RHI, in submission order — read off the
    /// executed list, not off the declaration, so it cannot drift from it.
    pub order: Vec<String>,
}

/// The v1 pass list with no window in it: the same [`BoxPass`] and the same
/// [`scene_graph`] the shell runs, with §4.5's readback pass appended where the
/// present would be.
///
/// This exists because the shell is windowed and therefore manual (§1.5), which
/// would otherwise leave the engine's own render path with no image coverage at
/// all. `gg-golden` renders through this, so the golden guards the frame the
/// screen gets rather than a lookalike assembled beside it.
pub struct OffscreenRenderer {
    rhi: gg_rhi::OffscreenRhi,
    pass: BoxPass,
    scene: ScenePass,
    ui: ui::UiPass,
    lighting: lighting::Lighting,
    luminance: luminance::Luminance,
    transients: Transients,
    readback: BufferHandle,
    extent: (u32, u32),
    content: Option<Content>,
    viewport: Option<Viewport>,
}

impl OffscreenRenderer {
    /// Bring up a surfaceless device at `extent` and upload the pass.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses: no device, or a failed upload.
    pub fn new(extent: (u32, u32)) -> Result<Self, RhiError> {
        let mut rhi = gg_rhi::OffscreenRhi::new(extent)?;
        let pass = BoxPass::new(&mut rhi)?;
        let scene = ScenePass::new(&mut rhi)?;
        let ui = ui::UiPass::new(&mut rhi)?;
        let lighting = lighting::Lighting::new(&mut rhi)?;
        let luminance = luminance::Luminance::new(&mut rhi)?;
        // One buffer for the renderer's life: a frame that allocated its own
        // readback would be measuring the allocator as much as the frame.
        let readback = rhi.create_buffer(&BufferDesc {
            name: "render.offscreen.readback",
            size: u64::from(extent.0) * u64::from(extent.1) * 4,
            kind: BufferKind::Readback,
        })?;
        Ok(OffscreenRenderer {
            rhi,
            pass,
            scene,
            ui,
            lighting,
            luminance,
            transients: Transients::default(),
            readback,
            extent,
            content: None,
            viewport: None,
        })
    }

    /// Put the frame inside `viewport` — see [`Renderer::set_viewport`].
    ///
    /// Here as well as on the windowed renderer because the windowed one is
    /// manual (§1.5): this is the only path that can prove the composite lands
    /// where it says, in a test with no window in it.
    pub fn set_viewport(&mut self, viewport: Option<Viewport>) {
        self.viewport = viewport;
    }

    /// The extent this renderer's projection is built from — see
    /// [`Renderer::view_extent`].
    #[must_use]
    pub fn view_extent(&self) -> (u32, u32) {
        view_extent(self.viewport, self.extent)
    }

    /// Map a pack — see [`Renderer::open_pack`].
    ///
    /// # Errors
    /// A file that will not open, or a pack the loader refuses by name.
    pub fn open_pack(&mut self, path: &Path) -> Result<(), ContentError> {
        self.content = Some(Content::open(path)?);
        Ok(())
    }

    /// Instances staged and draws issued by the pack pass last frame (§6 M10).
    ///
    /// Public because "ten thousand objects, four draws" is an exit claim, and a
    /// claim a harness cannot count is a claim nobody checks — `gg-golden`'s
    /// `field` scene asserts on this.
    #[must_use]
    pub fn draw_counts(&self) -> (usize, usize) {
        self.scene.counts()
    }

    /// This frame's luminance histogram, or `None` when `r.histogram` is off.
    /// Current rather than two frames behind: an offscreen submit blocks.
    #[must_use]
    pub fn luminance(&self) -> Option<&[u32; luminance::BINS]> {
        self.luminance.bins()
    }

    /// The pack — see [`Renderer::pack`].
    #[must_use]
    pub fn pack(&self) -> Option<&Content> {
        self.content.as_ref()
    }

    /// Re-open a rewritten pack — see [`Renderer::reload_pack`].
    ///
    /// # Errors
    /// A rewritten pack the loader refuses.
    pub fn reload_pack(&mut self) -> Result<bool, ContentError> {
        match &mut self.content {
            Some(content) => content.poll_reload(&mut self.rhi),
            None => Ok(false),
        }
    }

    /// Scene expansion — see [`Renderer::scenes`].
    #[must_use]
    pub fn scenes(&self) -> &dyn Scenes {
        match &self.content {
            Some(content) => content,
            None => &(),
        }
    }

    /// Hand the UI pass its coverage atlas — see [`Renderer::set_ui_atlas`].
    ///
    /// # Errors
    ///
    /// A bitmap whose length disagrees with its extent, or an allocation.
    pub fn set_ui_atlas(&mut self, coverage: &ui::Coverage<'_>) -> Result<(), RhiError> {
        self.ui.set_atlas(&mut self.rhi, coverage)
    }

    /// Live buffer and image allocations (§4.8).
    pub fn memory(&self) -> MemoryUse {
        self.rhi.memory()
    }

    /// Which device was chosen, and what it can do (§4.3).
    pub fn device(&self) -> &DeviceReport {
        self.rhi.device_report()
    }

    /// Per-pass GPU milliseconds from the last [`Self::frame`] (§4.8). Current
    /// rather than a frame behind: an offscreen render blocks until it retires.
    pub fn pass_timings(&self) -> &[PassTiming] {
        self.rhi.pass_timings()
    }

    /// One frame: depth prepass, forward opaque, post, the UI layer, readback.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses while compiling, recording or submitting.
    pub fn frame(
        &mut self,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
        ui: &[ui::UiVertex],
    ) -> Result<OffscreenFrame, RhiError> {
        stream(&mut self.content, &mut self.rhi, extracted)?;
        // One slot and a blocking submit per frame here, so nothing is in
        // flight to race either write.
        let frame_address = self.lighting.slot_address(0);
        let view_extent = view_extent(self.viewport, self.extent);
        let sun = self.lighting.plan(extracted, view, view_extent);
        let histogram = luminance::Luminance::enabled();
        let cascades = sun.map_or(0, |s| s.cascades().len());
        self.pass.build(extracted, frame_address);
        self.pass
            .build_shadow(extracted, frame_address, sun.as_ref());
        let content = self.content.as_ref();
        self.scene.build(
            &mut self.rhi,
            0,
            view_extent,
            extracted,
            view,
            content,
            frame_address,
            cascades,
        )?;
        report_draws(&self.scene, extracted);
        self.ui.write(&mut self.rhi, 0, ui)?;
        let ui_push = self.ui.push(self.extent);
        let mut frame = self.transients.frame(&mut self.rhi, self.extent)?;
        let backbuffer = frame.backbuffer();
        let scene = frame.color_at("scene.color", view_extent, SCENE_FORMAT)?;
        let depth = frame.depth_at("scene.depth", view_extent)?;
        let shadows = shadow_maps(&mut frame, sun)?;
        let shadow_textures: Vec<TextureIndex> =
            shadows.iter().filter_map(|id| frame.texture(*id)).collect();
        let grid = histogram
            .then(|| frame.color_at("luminance.grid", luminance::GRID, SCENE_FORMAT))
            .transpose()?;
        let into = frame.readback_buffer("render.offscreen.readback", self.readback);
        let post_push = self.pass.post_push(&frame, scene)?;

        let prepass_draws = prepass_draws(&self.pass, &self.scene);
        let shadow_draws: Vec<Vec<DrawSpec<'_>>> = (0..shadows.len())
            .map(|cascade| shadow_draws(&self.pass, &self.scene, cascade))
            .collect();
        let shadow_slices: Vec<&[DrawSpec<'_>]> = shadow_draws.iter().map(Vec::as_slice).collect();
        let forward_draws = forward_draws(&self.pass, &self.scene);
        let post_draws = [self.pass.post_draw(&post_push)];
        let samples = [scene];
        let forward_samples: Vec<graph::ResourceId> = shadows.clone();
        let mut declared = scene_graph(&SceneFrame {
            backbuffer,
            scene,
            depth,
            shadows: &shadows,
            clear: color,
            viewport: self.viewport,
            prepass_draws: &prepass_draws,
            shadow_draws: &shadow_slices,
            forward_draws: &forward_draws,
            post_draws: &post_draws,
            samples: &samples,
            forward_samples: &forward_samples,
        });
        let ui_draws: Vec<DrawSpec<'_>> = self.ui.draw(&ui_push).into_iter().collect();
        if !ui_draws.is_empty() {
            declared.push(ui_pass(backbuffer, &ui_draws));
        }
        // Readback last, so the image judged is the one the screen would get —
        // UI included (§4.10).
        declared.push(graph::readback_pass(backbuffer, into));
        let downsample_draws = [self.pass.downsample_draw(&post_push)];
        if let Some(grid) = grid {
            let grid_into = frame.readback_buffer("render.luminance", self.luminance.buffer(0));
            declared.extend(luminance_passes(
                grid,
                grid_into,
                &samples,
                &downsample_draws,
            ));
            self.luminance.mark(0);
        }

        let compiled = frame.compile(&declared)?;
        let dump = compiled.dump();
        let passes = compiled.passes();
        let order = passes.iter().map(|p| p.name.to_string()).collect();
        self.lighting.write(
            &mut self.rhi,
            0,
            view.view_projection(self.extent),
            &extracted.lights,
            &shadow_textures,
        )?;
        self.rhi.execute(&passes)?;
        // A blocking submit, so unlike the windowed path this is current rather
        // than two frames old.
        match histogram {
            true => self.luminance.read(&self.rhi, 0)?,
            false => self.luminance.clear(),
        }
        Ok(OffscreenFrame {
            pixels: self.rhi.map_buffer(self.readback)?.to_vec(),
            dump,
            order,
        })
    }

    /// Release everything and report leaks and validation messages (§4.3).
    pub fn shutdown(mut self) -> ShutdownReport {
        drop(self.transients.destroy(&mut self.rhi));
        drop(self.rhi.destroy_buffer(self.readback));
        if let Some(content) = &mut self.content {
            drop(content.destroy(&mut self.rhi));
        }
        drop(self.pass.destroy(&mut self.rhi));
        drop(self.scene.destroy(&mut self.rhi));
        drop(self.ui.destroy(&mut self.rhi));
        drop(self.lighting.destroy(&mut self.rhi));
        drop(self.luminance.destroy(&mut self.rhi));
        self.rhi.shutdown()
    }
}

/// Ask the pack for what this frame names, and move some of it onto the device.
///
/// Shared by both entry points rather than written twice: a pack that streamed
/// differently offscreen would make the golden suite (§4.10) a gate on a path
/// the screen never takes.
fn stream(
    content: &mut Option<Content>,
    rhi: &mut impl GpuHost,
    extracted: &Extracted,
) -> Result<(), RhiError> {
    let Some(content) = content else {
        return Ok(());
    };
    // Requested from what the frame *shows*, not from a manifest: a scene id
    // pulls its meshes in with it, and an asset nothing draws is never read off
    // the disk at all.
    for instance in &extracted.models {
        content.request(AssetId(instance.asset));
    }
    // The watcher's other end (§4.6). Absent from dist rather than disabled —
    // there is no `ggc` there to rewrite the file.
    #[cfg(feature = "hot-reload")]
    if let Err(refused) = content.poll_reload(rhi) {
        // The old pack is still mapped and still playing; a broken rebuild
        // belongs in the terminal, not in the player's session.
        tracing::error!(error = %refused, "pack reload refused — still drawing the last good one");
    }
    let budget = cvars::UPLOAD_BUDGET.int().max(0) as usize;
    content.pump(rhi, budget)?;
    Ok(())
}

/// Boxes then pack meshes, as one list. Two pipelines inside one pass rather
/// than a pass each: they write the same attachments, so a second prepass would
/// be a second set of derived barriers around no new resource.
/// One line per frame naming what batching bought: entities extracted, of which
/// culled, staged as instances, issued as draws. On a target of its own and at
/// `debug`, exactly like the per-tick hash (§5.6c) — a human's terminal must not
/// see sixty of these a second, and "ten thousand objects, four draws" is a
/// claim that should be countable rather than asserted (§6 M10).
fn report_draws(scene: &ScenePass, extracted: &Extracted) {
    if tracing::enabled!(target: "gg::draws", tracing::Level::DEBUG) {
        let (instances, draws) = scene.counts();
        tracing::debug!(
            target: "gg::draws",
            models = extracted.models.len(),
            culled = extracted.culled,
            instances,
            draws,
            lights = extracted.lights.len(),
            // The number that explains a corner of a room going dark: extract
            // dropped a light because a cap was reached (§6 M11).
            lights_dropped = extracted.lights_dropped,
        );
    }
}

fn prepass_draws<'a>(pass: &'a BoxPass, scene: &'a ScenePass) -> Vec<DrawSpec<'a>> {
    let mut draws = pass.draws(pass.prepass);
    draws.extend(scene.draws(scene.prepass()));
    draws
}

fn forward_draws<'a>(pass: &'a BoxPass, scene: &'a ScenePass) -> Vec<DrawSpec<'a>> {
    let mut draws = pass.draws(pass.forward);
    draws.extend(scene.draws(scene.forward()));
    draws
}

/// The same geometry through the sun's projection. Both pipelines, one pass: a
/// second shadow pass per pass-that-casts would be a second set of derived
/// barriers around one attachment.
///
/// **Unbiased**, and that is the fix rather than an omission (§6 M11's exit
/// row). Rasterizer depth bias corrects the wrong end — it moves the depth the
/// map *records*, so one receiver's bias follows the caster onto every other
/// receiver behind it — and it is not portable: for a float depth attachment the
/// constant term is scaled by an implementation-dependent `r`, which would make
/// a blessed reference (§4.10) a property of the driver. Both jobs are done at
/// the lookup instead, in `include/pbr.slang`.
/// Whether `instance` can cast into `cascade`, for a sun travelling `direction`.
///
/// A **cylinder** test, not a sphere one, and the difference is the whole point:
/// a caster outside the slab but between it and the sun still shadows into it.
/// So what is tested is the distance from the slab's axis — the light direction
/// through its centre — with the along-light extent checked separately against
/// the depth range `lighting::fit` built the projection with.
fn casts_into(instance: &Instance, cascade: &lighting::Cascade, direction: render::Vec3) -> bool {
    let to = instance.offset - cascade.centre;
    let along = to.dot(direction);
    let reach = cascade.radius + instance.radius;
    // `radius * 2` each way: the eye sits two radii up-light of the centre and
    // the far plane four, so that is exactly the depth the map records.
    (to - direction * along).length() <= reach && along.abs() <= cascade.radius * 2.0 + reach
}

/// One depth attachment per cascade, or none when nothing casts (§6 M15.3).
///
/// Separate images rather than one array texture, and that is a deliberate line
/// held: a layered attachment would need array layers in `ImageDesc`, per-layer
/// views, and a layer index on the graph's depth binding — RHI surface added for
/// a saving the shadow pass does not get, since the geometry has to be recorded
/// per cascade either way. Four images cost four bindless slots and nothing else.
fn shadow_maps(
    frame: &mut graph::Frame<'_>,
    sun: Option<lighting::Sun>,
) -> Result<Vec<graph::ResourceId>, RhiError> {
    let Some(sun) = sun else {
        return Ok(Vec::new());
    };
    // Named per cascade so a graph dump names what it allocated rather than the
    // same string four times — the dump is read to find out what a frame did.
    const NAMES: [&str; lighting::MAX_CASCADES] = [
        "scene.shadow.0",
        "scene.shadow.1",
        "scene.shadow.2",
        "scene.shadow.3",
    ];
    let extent = (sun.size, sun.size);
    sun.cascades()
        .iter()
        .zip(NAMES)
        .map(|(_, name)| frame.shadow(name, extent))
        .collect()
}

fn shadow_draws<'a>(pass: &'a BoxPass, scene: &'a ScenePass, cascade: usize) -> Vec<DrawSpec<'a>> {
    let mut draws = pass.shadow_draws(cascade);
    draws.extend(scene.shadow_draws(cascade));
    draws
}

/// The boxes, and the four pipelines that draw them: prepass, shadow, forward,
/// post.
struct BoxPass {
    prepass: PipelineHandle,
    forward: PipelineHandle,
    shadow: PipelineHandle,
    post: PipelineHandle,
    /// The luminance resample: the post pass's vertex stage into a small float
    /// target, without the tonemap curve (§6 M11).
    downsample: PipelineHandle,
    vertices: BufferHandle,
    indices: BufferHandle,
    vertex_address: DeviceAddress,
    index_count: u32,
    /// Reused across frames. The push constants have to outlive the [`DrawSpec`]s
    /// that borrow them, and extract already refuses to allocate per frame — a
    /// buffer beside it that did would undo that.
    pushes: Vec<shader::UglyPush>,
    /// One list per cascade, culled — see [`BoxPass::build_shadow`].
    shadow_pushes: Vec<Vec<shader::UglyPush>>,
}

/// The slice of an RHI a pass — or a resident asset — needs to put itself on
/// the GPU.
///
/// The same shape demo 02's `SceneHost` has, and for the same reason: §3 keeps
/// a backend abstraction out of `gg-rhi`, so a crate that wants to run one pass
/// over both entry points writes its own two-line bridge. What it buys here is
/// that the offscreen test builds the *same* pass the shell does, and that
/// [`Residency`](residency::Residency) uploads through the same one.
///
/// Every method forwards verbatim; see the like-named one on
/// [`Rhi`](gg_rhi::Rhi) for what each contracts and refuses.
pub trait GpuHost {
    /// See [`gg_rhi::Rhi::create_buffer`].
    fn create_buffer(&mut self, desc: &BufferDesc<'_>) -> Result<BufferHandle, RhiError>;
    /// See [`gg_rhi::Rhi::upload_buffer`].
    fn upload_buffer(&mut self, h: BufferHandle, offset: u64, b: &[u8]) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::write_buffer`].
    fn write_buffer(&mut self, h: BufferHandle, offset: u64, b: &[u8]) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::flush_uploads`].
    fn flush_uploads(&mut self) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::buffer_address`].
    fn buffer_address(&self, handle: BufferHandle) -> Result<DeviceAddress, RhiError>;
    /// See [`gg_rhi::Rhi::map_buffer`].
    fn map_buffer(&self, handle: BufferHandle) -> Result<&[u8], RhiError>;
    /// See [`gg_rhi::Rhi::create_image`].
    fn create_image(&mut self, desc: &ImageDesc<'_>) -> Result<ImageHandle, RhiError>;
    /// See [`gg_rhi::Rhi::upload_image`].
    fn upload_image(
        &mut self,
        handle: ImageHandle,
        level: u32,
        bytes: &[u8],
    ) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::register_texture`].
    fn register_texture(&mut self, handle: ImageHandle) -> Result<TextureIndex, RhiError>;
    /// See [`gg_rhi::Rhi::create_pipeline`].
    fn create_pipeline(&mut self, desc: &PipelineDesc<'_>) -> Result<PipelineHandle, RhiError>;
    /// See [`gg_rhi::Rhi::destroy_pipeline`].
    fn destroy_pipeline(&mut self, handle: PipelineHandle) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::destroy_buffer`].
    fn destroy_buffer(&mut self, handle: BufferHandle) -> Result<(), RhiError>;
    /// See [`gg_rhi::Rhi::destroy_image`].
    fn destroy_image(&mut self, handle: ImageHandle) -> Result<(), RhiError>;
}

/// Both entry points, verbatim: the trait exists to name the overlap, not to
/// add behaviour to it.
macro_rules! pass_host {
    ($t:ty) => {
        impl GpuHost for $t {
            fn create_buffer(&mut self, desc: &BufferDesc<'_>) -> Result<BufferHandle, RhiError> {
                <$t>::create_buffer(self, desc)
            }
            fn upload_buffer(
                &mut self,
                h: BufferHandle,
                offset: u64,
                b: &[u8],
            ) -> Result<(), RhiError> {
                <$t>::upload_buffer(self, h, offset, b)
            }
            fn write_buffer(
                &mut self,
                h: BufferHandle,
                offset: u64,
                b: &[u8],
            ) -> Result<(), RhiError> {
                <$t>::write_buffer(self, h, offset, b)
            }
            fn flush_uploads(&mut self) -> Result<(), RhiError> {
                <$t>::flush_uploads(self)
            }
            fn buffer_address(&self, handle: BufferHandle) -> Result<DeviceAddress, RhiError> {
                <$t>::buffer_address(self, handle)
            }
            fn map_buffer(&self, handle: BufferHandle) -> Result<&[u8], RhiError> {
                <$t>::map_buffer(self, handle)
            }
            fn create_image(&mut self, desc: &ImageDesc<'_>) -> Result<ImageHandle, RhiError> {
                <$t>::create_image(self, desc)
            }
            fn upload_image(
                &mut self,
                handle: ImageHandle,
                level: u32,
                bytes: &[u8],
            ) -> Result<(), RhiError> {
                <$t>::upload_image(self, handle, level, bytes)
            }
            fn register_texture(&mut self, handle: ImageHandle) -> Result<TextureIndex, RhiError> {
                <$t>::register_texture(self, handle)
            }
            fn create_pipeline(
                &mut self,
                desc: &PipelineDesc<'_>,
            ) -> Result<PipelineHandle, RhiError> {
                <$t>::create_pipeline(self, desc)
            }
            fn destroy_pipeline(&mut self, handle: PipelineHandle) -> Result<(), RhiError> {
                <$t>::destroy_pipeline(self, handle)
            }
            fn destroy_buffer(&mut self, handle: BufferHandle) -> Result<(), RhiError> {
                <$t>::destroy_buffer(self, handle)
            }
            fn destroy_image(&mut self, handle: ImageHandle) -> Result<(), RhiError> {
                <$t>::destroy_image(self, handle)
            }
        }
    };
}

pass_host!(Rhi);
pass_host!(gg_rhi::OffscreenRhi);

impl BoxPass {
    /// Upload the box and build the pipelines. One flush, at startup.
    fn new(rhi: &mut impl GpuHost) -> Result<Self, RhiError> {
        let (vertices, indices) = unit_box();
        let vertex_bytes = bytemuck::cast_slice(&vertices);
        let index_bytes = bytemuck::cast_slice(&indices);

        let vertex_buffer = rhi.create_buffer(&BufferDesc {
            name: "render.box.vertices",
            size: vertex_bytes.len() as u64,
            kind: BufferKind::Storage,
        })?;
        let index_buffer = rhi.create_buffer(&BufferDesc {
            name: "render.box.indices",
            size: index_bytes.len() as u64,
            kind: BufferKind::Index,
        })?;
        rhi.upload_buffer(vertex_buffer, 0, vertex_bytes)?;
        rhi.upload_buffer(index_buffer, 0, index_bytes)?;
        rhi.flush_uploads()?;

        Ok(BoxPass {
            prepass: rhi.create_pipeline(&prepass_desc())?,
            forward: rhi.create_pipeline(&forward_desc())?,
            shadow: rhi.create_pipeline(&shadow_desc())?,
            post: rhi.create_pipeline(&post_desc())?,
            downsample: rhi.create_pipeline(&downsample_desc())?,
            vertices: vertex_buffer,
            indices: index_buffer,
            vertex_address: rhi.buffer_address(vertex_buffer)?,
            index_count: indices.len() as u32,
            pushes: Vec::new(),
            shadow_pushes: Vec::new(),
        })
    }

    /// Rebuild this frame's push constants.
    fn build(&mut self, extracted: &Extracted, frame: DeviceAddress) {
        let address = self.vertex_address;
        self.pushes.clear();
        self.pushes.extend(
            extracted
                .instances
                .iter()
                .map(|instance| push_for(address, frame, instance)),
        );
    }

    /// This frame's shadow pushes: one list per cascade, each holding only the
    /// boxes that can cast *into* that cascade (§6 M15.3).
    ///
    /// The cull is what keeps four cascades from being four times the shadow
    /// pass. It is a cylinder test, not a sphere one: a caster outside the slab
    /// but between it and the sun still shadows into it, so what is tested is
    /// the distance from the slab's axis, with the along-light extent checked
    /// separately against the depth range `Cascade` was built with.
    fn build_shadow(
        &mut self,
        extracted: &Extracted,
        frame: DeviceAddress,
        sun: Option<&lighting::Sun>,
    ) {
        let address = self.vertex_address;
        let cascades = sun.map_or(&[][..], |s| s.cascades());
        self.shadow_pushes.resize_with(cascades.len(), Vec::new);
        self.shadow_pushes.truncate(cascades.len());
        for (index, (pushes, cascade)) in self.shadow_pushes.iter_mut().zip(cascades).enumerate() {
            let direction = sun.map_or(render::Vec3::NEG_Y, |s| s.direction);
            pushes.clear();
            pushes.extend(
                extracted
                    .instances
                    .iter()
                    .filter(|instance| casts_into(instance, cascade, direction))
                    .map(|instance| {
                        let mut push = push_for(address, frame, instance);
                        push.cascade = index as u32;
                        push
                    }),
            );
        }
    }

    /// The boxes that reach cascade `cascade`, through the shadow pipeline.
    fn shadow_draws(&self, cascade: usize) -> Vec<DrawSpec<'_>> {
        let pushes = self
            .shadow_pushes
            .get(cascade)
            .map_or(&[][..], Vec::as_slice);
        self.draws_of(self.shadow, pushes)
    }

    /// The frame's boxes, drawn by `pipeline`.
    ///
    /// A draw call per box, which is the honest cost while the Ugly Game draws
    /// a few hundred; instancing is a §4.6 vertex-format question rather than a
    /// graph one, and it belongs with real meshes.
    fn draws(&self, pipeline: PipelineHandle) -> Vec<DrawSpec<'_>> {
        self.draws_of(pipeline, &self.pushes)
    }

    fn draws_of<'a>(
        &'a self,
        pipeline: PipelineHandle,
        pushes: &'a [shader::UglyPush],
    ) -> Vec<DrawSpec<'a>> {
        pushes
            .iter()
            .map(|push| DrawSpec {
                pipeline,
                push_constants: bytemuck::bytes_of(push),
                count: self.index_count,
                index_buffer: Some(self.indices),
                indirect: None,
                depth_bias: None,
            })
            .collect()
    }

    /// Where the post pass reads the scene attachment from, and what exposure it
    /// applies (§6 M11).
    fn post_push(
        &self,
        frame: &graph::Frame<'_>,
        scene: graph::ResourceId,
    ) -> Result<post_shader::PostPush, RhiError> {
        let index = frame.texture(scene).ok_or_else(|| {
            RhiError::Loader("the scene attachment has no bindless slot to sample".into())
        })?;
        Ok(post_shader::PostPush::new(
            index.get(),
            Sampler::NearestClamp.index(),
            cvars::EXPOSURE.float() as f32,
            0,
        ))
    }

    fn post_draw<'a>(&self, push: &'a post_shader::PostPush) -> DrawSpec<'a> {
        DrawSpec {
            pipeline: self.post,
            push_constants: bytemuck::bytes_of(push),
            count: FULLSCREEN_VERTICES,
            index_buffer: None,
            indirect: None,
            depth_bias: None,
        }
    }

    /// The luminance resample (§6 M11) — the same fullscreen triangle as the
    /// post pass, into a small float target and without the curve.
    fn downsample_draw<'a>(&self, push: &'a post_shader::PostPush) -> DrawSpec<'a> {
        DrawSpec {
            pipeline: self.downsample,
            push_constants: bytemuck::bytes_of(push),
            count: FULLSCREEN_VERTICES,
            index_buffer: None,
            indirect: None,
            depth_bias: None,
        }
    }

    /// Release the pipelines and both buffers.
    fn destroy(self, rhi: &mut impl GpuHost) -> Result<(), RhiError> {
        rhi.destroy_pipeline(self.downsample)?;
        rhi.destroy_pipeline(self.prepass)?;
        rhi.destroy_pipeline(self.forward)?;
        rhi.destroy_pipeline(self.shadow)?;
        rhi.destroy_pipeline(self.post)?;
        rhi.destroy_buffer(self.vertices)?;
        rhi.destroy_buffer(self.indices)
    }
}

/// The luminance resample and the copy that brings it back (§6 M11).
///
/// Two passes rather than one because the readback *is* a pass in this graph
/// (§4.5) — which is what gives the copy a derived dependency on the draw
/// instead of a race the frame usually wins.
fn luminance_passes<'a>(
    grid: graph::ResourceId,
    into: graph::ResourceId,
    samples: &'a [graph::ResourceId],
    draws: &'a [DrawSpec<'a>],
) -> [Declared<'a>; 2] {
    [
        Declared {
            name: "luminance",
            body: Body::Draw {
                // `Keep`, like the post pass: a fullscreen triangle writes every
                // texel, so a clear would be a target's worth of thrown-away
                // writes.
                color: Some((grid, Load::Keep)),
                depth: None,
                viewport: None,
                samples,
                draws,
            },
        },
        graph::readback_pass(grid, into),
    ]
}

/// The UI layer over a resolved frame: alpha-blended, depth-free, keeping what
/// is already there. Declared as a pass rather than appended to the post pass's
/// draws because it targets a different pipeline state, and because M13's
/// `gg-ui` gets a pass of its own in the graph either way (§4.9).
pub fn ui_pass<'a>(backbuffer: graph::ResourceId, draws: &'a [DrawSpec<'a>]) -> Declared<'a> {
    Declared {
        name: "ui",
        body: Body::Draw {
            color: Some((backbuffer, Load::Keep)),
            depth: None,
            // The whole target, never the scene's viewport: the panels that
            // frame a viewport are exactly the pixels outside it (§6 M15).
            viewport: None,
            // The coverage atlas is an uploaded texture like any material's,
            // already in a sampled layout — not a graph resource, so there is
            // no transition for the graph to derive.
            samples: &[],
            draws,
        },
    }
}

/// Everything one frame's [`scene_graph`] needs, gathered so the two entry
/// points assemble it identically. A struct rather than nine arguments because
/// it grew a shadow pass and the next thing to grow it should not have to
/// re-argue the signature.
pub struct SceneFrame<'a> {
    /// Where the frame lands.
    pub backbuffer: graph::ResourceId,
    /// The HDR scene attachment.
    pub scene: graph::ResourceId,
    /// The camera's depth buffer.
    pub depth: graph::ResourceId,
    /// One depth buffer per cascade, nearest first, empty when nothing casts
    /// (§6 M15.3).
    pub shadows: &'a [graph::ResourceId],
    /// Linear clear for the scene attachment.
    pub clear: [f32; 4],
    /// Where the post pass lands the scene in the backbuffer. `None` is all of
    /// it — a window showing nothing but the game. The scene and depth
    /// attachments must already be this size: the viewport crops the *resolve*,
    /// while what makes the picture right for a narrower rectangle is that the
    /// projection was built from its aspect.
    pub viewport: Option<Viewport>,
    /// Depth-prepass draws.
    pub prepass_draws: &'a [DrawSpec<'a>],
    /// Shadow-pass draws, one list per entry in `shadows` and in the same
    /// order. Shorter than `shadows` is a cascade drawn empty, which is a black
    /// map and therefore a fully lit one — not a crash, and not a shadow.
    pub shadow_draws: &'a [&'a [DrawSpec<'a>]],
    /// Forward-pass draws.
    pub forward_draws: &'a [DrawSpec<'a>],
    /// The one fullscreen resolve.
    pub post_draws: &'a [DrawSpec<'a>],
    /// What the post pass samples.
    pub samples: &'a [graph::ResourceId],
    /// What the forward pass samples — the shadow map, when there is one.
    pub forward_samples: &'a [graph::ResourceId],
}

/// The §4.5 v1 scene graph: shadow → depth prepass → forward opaque →
/// fullscreen post.
///
/// A free function rather than a method because it is the *shape*, and the
/// shape is what a second caller wants — the golden harness declares these and
/// appends a readback pass (§4.10), and a shape it had to restate would be a
/// shape that could disagree with the screen's.
///
/// **The shadow pass is declared only when something casts.** A frame with no
/// directional light does not allocate a shadow map, does not clear it and does
/// not name it — so the graph dump is the frame rather than a superset of every
/// frame, and an unlit scene pays nothing for a feature it is not using.
#[must_use]
pub fn scene_graph<'a>(frame: &SceneFrame<'a>) -> Vec<Declared<'a>> {
    let mut declared = Vec::with_capacity(4 + frame.shadows.len());
    // One pass per cascade, nearest first. They are independent — different
    // attachment, different draw list, no read of each other — so the graph's
    // derived barriers put nothing between them.
    const SHADOW_NAMES: [&str; lighting::MAX_CASCADES] =
        ["shadow.0", "shadow.1", "shadow.2", "shadow.3"];
    for ((index, shadow), name) in frame.shadows.iter().enumerate().zip(SHADOW_NAMES) {
        declared.push(Declared {
            name,
            body: Body::Draw {
                color: None,
                // Stored, unlike the prepass's: the forward pass samples it.
                depth: Some((*shadow, DepthUse::WriteStore)),
                viewport: None,
                samples: &[],
                draws: frame.shadow_draws.get(index).copied().unwrap_or(&[]),
            },
        });
    }
    declared.push(Declared {
        name: "depth-prepass",
        body: Body::Draw {
            color: None,
            depth: Some((frame.depth, DepthUse::WriteStore)),
            // Every pass up to the post owns an attachment sized to the
            // viewport already, so all three draw over the whole of theirs.
            viewport: None,
            samples: &[],
            draws: frame.prepass_draws,
        },
    });
    declared.push(Declared {
        name: "forward-opaque",
        body: Body::Draw {
            color: Some((frame.scene, Load::Clear(frame.clear))),
            depth: Some((frame.depth, DepthUse::Test)),
            viewport: None,
            // The shadow map is read through the bindless array like any
            // texture, so the graph would see no dependency at all unless the
            // pass declares it — which is exactly the hazard §4.5 warns that an
            // index hides.
            samples: frame.forward_samples,
            draws: frame.forward_draws,
        },
    });
    declared.push(Declared {
        name: "post",
        body: Body::Draw {
            // `Keep` when the resolve covers the target: the pass writes every
            // pixel of it from a fullscreen triangle, so clearing first would be
            // a full target's worth of writes thrown away. A viewport is exactly
            // the case where that stops being true — the pixels outside it are
            // written by nothing in this graph, and an unwritten backbuffer is
            // whatever the last frame in that slot left there.
            color: Some((
                frame.backbuffer,
                match frame.viewport {
                    Some(_) => Load::Clear(LETTERBOX),
                    None => Load::Keep,
                },
            )),
            depth: None,
            viewport: frame.viewport,
            samples: frame.samples,
            draws: frame.post_draws,
        },
    });
    declared
}

/// The extent a frame's projection and attachments are sized from, given the
/// surface it presents into. One function because both renderers and the
/// shell's culling have to agree on it exactly — a frustum and a projection
/// built from different aspects is geometry that pops in at the frame edge.
fn view_extent(viewport: Option<Viewport>, surface: (u32, u32)) -> (u32, u32) {
    match viewport.map(|v| v.clamped(surface)) {
        // A zero-width viewport allocates nothing and draws nothing; the
        // attachment pool refuses a zero extent, so fall back to the surface
        // and let the scissor discard the frame instead.
        Some(v) if v.width > 0 && v.height > 0 => (v.width, v.height),
        _ => surface,
    }
}

/// What surrounds a viewport that does not cover the backbuffer. Opaque black
/// rather than the scene's clear: the border of a composited frame is not more
/// sky, and a host drawing panels over it (§6 M15) covers this anyway.
const LETTERBOX: [f32; 4] = [0.0, 0.0, 0.0, 1.0];

/// The depth prepass: position only, no colour, depth stored for the forward
/// pass to test against.
fn prepass_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "ugly.prepass",
        vs_spirv: shader::VS_DEPTH_SPIRV,
        vs_entry: shader::VS_DEPTH_ENTRY,
        fs_spirv: shader::FS_DEPTH_SPIRV,
        fs_entry: shader::FS_DEPTH_ENTRY,
        push_constant_size: core::mem::size_of::<shader::UglyPush>() as u32,
        color: ColorTarget::None,
        blend: Blend::Off,
        depth: DepthMode::Write,
        depth_bias: false,
    }
}

/// The forward pass, into the scene attachment rather than the backbuffer: the
/// post pass is what reaches the screen. Depth is tested, not written — the
/// prepass placed every fragment already, and reverse-Z's `GREATER_OR_EQUAL`
/// lets the same geometry re-draw exactly where it landed.
fn forward_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "ugly.forward",
        vs_spirv: shader::VS_MAIN_SPIRV,
        vs_entry: shader::VS_MAIN_ENTRY,
        fs_spirv: shader::FS_MAIN_SPIRV,
        fs_entry: shader::FS_MAIN_ENTRY,
        push_constant_size: core::mem::size_of::<shader::UglyPush>() as u32,
        color: ColorTarget::Format(SCENE_FORMAT),
        blend: Blend::Off,
        depth: DepthMode::TestOnly,
        depth_bias: false,
    }
}

/// The shadow pass: the same boxes through the sun's projection, depth only and
/// **unbiased** — see [`shadow_draws`] for why the rasterizer does not do it.
fn shadow_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "ugly.shadow",
        vs_spirv: shader::VS_SHADOW_SPIRV,
        vs_entry: shader::VS_SHADOW_ENTRY,
        fs_spirv: shader::FS_DEPTH_SPIRV,
        fs_entry: shader::FS_DEPTH_ENTRY,
        push_constant_size: core::mem::size_of::<shader::UglyPush>() as u32,
        color: ColorTarget::None,
        blend: Blend::Off,
        depth: DepthMode::Write,
        depth_bias: false,
    }
}

/// The fullscreen post pass, onto whatever the frame lands in.
fn post_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "post",
        vs_spirv: post_shader::VS_MAIN_SPIRV,
        vs_entry: post_shader::VS_MAIN_ENTRY,
        fs_spirv: post_shader::FS_MAIN_SPIRV,
        fs_entry: post_shader::FS_MAIN_ENTRY,
        push_constant_size: core::mem::size_of::<post_shader::PostPush>() as u32,
        color: ColorTarget::Backbuffer,
        blend: Blend::Off,
        depth: DepthMode::Off,
        depth_bias: false,
    }
}

/// The luminance resample, into its own small float target. The scene's format
/// rather than the backbuffer's: what the histogram is about is radiance, and an
/// 8-bit sRGB target would clip and encode it before the CPU ever saw it.
fn downsample_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "luminance",
        vs_spirv: post_shader::VS_MAIN_SPIRV,
        vs_entry: post_shader::VS_MAIN_ENTRY,
        fs_spirv: post_shader::FS_DOWNSAMPLE_SPIRV,
        fs_entry: post_shader::FS_DOWNSAMPLE_ENTRY,
        push_constant_size: core::mem::size_of::<post_shader::PostPush>() as u32,
        color: ColorTarget::Format(SCENE_FORMAT),
        blend: Blend::Off,
        depth: DepthMode::Off,
        depth_bias: false,
    }
}

/// The graph's scene attachment format. `Rgba16F` since M11: radiance leaves the
/// forward pass unbounded above 1.0 and the tonemapper is what brings it down,
/// so an 8-bit target would clip every highlight before the curve that exists to
/// shape them ever ran. It is also linear, unlike the sRGB target it replaced —
/// the post pass therefore reads exactly what was written and encodes once, on
/// the way to the screen.
const SCENE_FORMAT: ImageFormat = ImageFormat::Rgba16F;

/// The fullscreen triangle the post pass draws — three shader-generated
/// vertices, no buffer.
const FULLSCREEN_VERTICES: u32 = 3;

/// Push constants for one box.
///
/// No matrix: Vulkan guarantees 128 bytes of push and this pass has one push per
/// box, so the object-to-clip product is assembled in the vertex shader from the
/// projection the frame buffer carries. `ugly.slang` states the trade and why
/// the pack pass makes the opposite one.
fn push_for(
    vertices: DeviceAddress,
    frame: DeviceAddress,
    instance: &Instance,
) -> shader::UglyPush {
    shader::UglyPush::new(
        vertices,
        frame,
        srgb_to_linear(instance.color),
        instance.rotation.to_array(),
        instance.offset.extend(0.0).to_array(),
        instance.half_extent.extend(0.0).to_array(),
        // Cascade 0 unless `build_shadow` overwrites it; the forward and prepass
        // pipelines never read the field.
        0,
    )
}

/// The sRGB EOTF (IEC 61966-2-1) evaluated at every byte: `c/12.92` up to
/// `0.04045`, `((c + 0.055)/1.055)^2.4` above it. A table because the domain is
/// 256 values and `powf` is banned engine-wide (§3) — exact, portable, and
/// cheaper than either form. `the_transfer_function_is_srgb` checks every entry
/// against the formula in `f64`; `ui.slang`'s `unpack` is the GPU-side twin.
#[rustfmt::skip]
const SRGB_EOTF: [f32; 256] = [
    0.0, 0.000303527, 0.000607054, 0.000910581, 0.001214108, 0.001517635,
    0.001821162, 0.0021246888, 0.002428216, 0.0027317428, 0.00303527, 0.0033465358,
    0.0036765074, 0.004024717, 0.004391442, 0.0047769533, 0.0051815165, 0.0056053917,
    0.006048833, 0.0065120906, 0.00699541, 0.007499032, 0.008023193, 0.008568126,
    0.009134059, 0.009721218, 0.010329823, 0.010960094, 0.011612245, 0.012286488,
    0.0129830325, 0.013702083, 0.014443844, 0.015208514, 0.015996294, 0.016807375,
    0.017641954, 0.01850022, 0.019382361, 0.020288562, 0.02121901, 0.022173885,
    0.023153367, 0.024157632, 0.02518686, 0.026241222, 0.027320892, 0.02842604,
    0.029556835, 0.030713445, 0.031896032, 0.033104766, 0.034339808, 0.035601314,
    0.03688945, 0.038204372, 0.039546236, 0.0409152, 0.04231141, 0.04373503,
    0.045186203, 0.046665087, 0.048171826, 0.049706567, 0.051269457, 0.052860647,
    0.054480277, 0.05612849, 0.05780543, 0.059511237, 0.061246052, 0.063010015,
    0.064803265, 0.06662594, 0.06847817, 0.070360094, 0.07227185, 0.07421357,
    0.07618538, 0.07818742, 0.08021982, 0.08228271, 0.08437621, 0.08650046,
    0.08865558, 0.09084171, 0.093058966, 0.09530747, 0.09758735, 0.099898726,
    0.10224173, 0.104616486, 0.107023105, 0.10946171, 0.11193243, 0.114435375,
    0.116970666, 0.11953843, 0.122138776, 0.12477182, 0.12743768, 0.13013647,
    0.13286832, 0.13563333, 0.13843161, 0.14126329, 0.14412847, 0.14702727,
    0.14995979, 0.15292615, 0.15592647, 0.15896083, 0.16202937, 0.1651322,
    0.1682694, 0.17144111, 0.1746474, 0.17788842, 0.18116425, 0.18447499,
    0.18782078, 0.19120169, 0.19461784, 0.19806932, 0.20155625, 0.20507874,
    0.20863687, 0.21223076, 0.2158605, 0.2195262, 0.22322796, 0.22696587,
    0.23074006, 0.23455058, 0.23839757, 0.24228112, 0.24620132, 0.25015828,
    0.2541521, 0.25818285, 0.26225066, 0.2663556, 0.2704978, 0.2746773,
    0.27889428, 0.28314874, 0.28744084, 0.29177064, 0.29613826, 0.30054379,
    0.3049873, 0.30946892, 0.31398872, 0.31854677, 0.3231432, 0.3277781,
    0.33245152, 0.33716363, 0.34191442, 0.34670407, 0.3515326, 0.35640013,
    0.3613068, 0.3662526, 0.3712377, 0.37626213, 0.38132602, 0.38642943,
    0.39157248, 0.39675522, 0.40197778, 0.4072402, 0.4125426, 0.41788507,
    0.42326766, 0.4286905, 0.43415365, 0.43965718, 0.4452012, 0.4507858,
    0.45641103, 0.462077, 0.4677838, 0.47353148, 0.47932017, 0.48514995,
    0.49102086, 0.49693298, 0.5028865, 0.50888133, 0.5149177, 0.52099556,
    0.5271151, 0.5332764, 0.5394795, 0.54572445, 0.55201143, 0.5583404,
    0.5647115, 0.57112485, 0.57758045, 0.58407843, 0.59061885, 0.59720176,
    0.60382736, 0.61049557, 0.6172066, 0.6239604, 0.63075715, 0.63759685,
    0.6444797, 0.65140563, 0.65837485, 0.6653873, 0.67244315, 0.6795425,
    0.6866853, 0.69387174, 0.7011019, 0.70837575, 0.7156935, 0.7230551,
    0.73046076, 0.7379104, 0.7454042, 0.7529422, 0.7605245, 0.76815116,
    0.7758222, 0.7835378, 0.7912979, 0.7991027, 0.80695224, 0.8148466,
    0.82278574, 0.8307699, 0.838799, 0.8468732, 0.8549926, 0.8631572,
    0.8713671, 0.8796224, 0.8879231, 0.8962694, 0.9046612, 0.91309863,
    0.92158186, 0.9301109, 0.9386857, 0.9473065, 0.9559733, 0.9646863,
    0.9734453, 0.9822506, 0.9911021, 1.0,
];

/// `0x00RRGGBB` → linear rgb, with alpha unused.
///
/// The colour a game writes is sRGB bytes; everything downstream is linear —
/// the material tint it multiplies (`scene.rs`) and light colour (`lighting.rs`)
/// both are — so the transfer function here is a systematic shading term, not a
/// tint fudge. Byte-indexed [`SRGB_EOTF`], so it is the exact curve.
fn srgb_to_linear(color: u32) -> [f32; 4] {
    // `& 0xff` is the table's whole domain, so the index cannot escape it.
    let channel = |shift: u32| SRGB_EOTF[((color >> shift) & 0xff) as usize];
    [channel(16), channel(8), channel(0), 1.0]
}

/// A box of half-extent 1 — the instance's scale is what gives it a size. 24
/// vertices so every face carries its own normal, 36 indices.
fn unit_box() -> (Vec<Vertex>, Vec<u32>) {
    // (normal, u axis, v axis) per face, u x v pointing outward.
    const FACES: [([f32; 3], [f32; 3], [f32; 3]); 6] = [
        ([1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]),
        ([-1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]),
        ([0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, -1.0]),
        ([0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]),
        ([0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
        ([0.0, 0.0, -1.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
    ];
    const CORNERS: [(f32, f32); 4] = [(-1.0, -1.0), (1.0, -1.0), (1.0, 1.0), (-1.0, 1.0)];

    let mut vertices = Vec::with_capacity(24);
    let mut indices = Vec::with_capacity(36);
    for (normal, u_axis, v_axis) in FACES {
        let base = vertices.len() as u32;
        for (u, v) in CORNERS {
            vertices.push(Vertex {
                position: [
                    normal[0] + u * u_axis[0] + v * v_axis[0],
                    normal[1] + u * u_axis[1] + v * v_axis[1],
                    normal[2] + u * u_axis[2] + v * v_axis[2],
                ],
                normal,
            });
        }
        indices.extend_from_slice(&[base, base + 1, base + 2, base, base + 2, base + 3]);
    }
    (vertices, indices)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn the_box_is_closed_and_its_normals_point_outward() {
        let (vertices, indices) = unit_box();
        assert_eq!(vertices.len(), 24);
        assert_eq!(indices.len(), 36);
        for v in &vertices {
            for axis in v.position {
                assert!(
                    (axis.abs() - 1.0).abs() < 1e-6,
                    "corner at {:?}",
                    v.position
                );
            }
            let dot = v.position[0] * v.normal[0]
                + v.position[1] * v.normal[1]
                + v.position[2] * v.normal[2];
            assert!(dot > 0.0, "normal {:?} faces inward", v.normal);
        }
    }

    #[test]
    fn the_near_plane_maps_to_one_and_the_far_distance_to_zero() {
        // Reverse-Z, the §2-locked convention, checked where a projection is
        // actually built rather than only where it is defined: a matrix assembled
        // the ordinary way renders a scene that is subtly, consistently wrong.
        let view = View::default();
        let clip = view.view_projection((640, 360));
        let near = clip * render::Vec4::new(0.0, 0.0, -view.near, 1.0);
        let far = clip * render::Vec4::new(0.0, 0.0, -1.0e9, 1.0);
        assert!((near.z / near.w - 1.0).abs() < 1e-5, "near maps to 1");
        assert!((far.z / far.w).abs() < 1e-5, "the far distance maps to 0");
    }

    #[test]
    fn a_yawed_view_looks_where_the_yaw_says() {
        let view = View {
            yaw: core::f32::consts::FRAC_PI_2,
            ..View::default()
        };
        // +90° of yaw about +Y turns the -Z forward axis onto -X.
        let forward = view.rotation() * render::Vec3::NEG_Z;
        assert!(
            (forward - render::Vec3::NEG_X).length() < 1e-6,
            "{forward:?}"
        );
    }

    /// The whole path with no window in it, through the whole graph: a game
    /// component, extract's narrowing, the push constants, a depth prepass, the
    /// forward pass over its result, the fullscreen resolve, and pixels back
    /// through §4.5's readback pass (§1.5 — the only rendering an automated tier
    /// is allowed to do).
    ///
    /// This is the v1 pass list end to end. The shell runs the same four minus
    /// the readback, and the shell is windowed and therefore manual — so this is
    /// where the derived barriers between prepass, forward and post are proven.
    /// One red box, dead ahead, and a sun to see it by.
    fn one_lit_box(sun: bool) -> Extracted {
        use gg_ecs::World;
        use gg_ecs::boundary::{Light, Renderable};
        use gg_math::sim;

        let mut world = World::new();
        world.register::<Renderable>().unwrap();
        world.register::<Light>().unwrap();
        let entity = world.spawn();
        world
            .insert(
                entity,
                // Dead ahead of an unrotated eye, big enough to cover the middle
                // and small enough to leave the corners clear.
                Renderable::boxed(
                    sim::DVec3::new(0.0, 0.0, -4.0),
                    sim::Vec3::splat(1.0),
                    0x00ff_0000,
                ),
            )
            .unwrap();
        if sun {
            let light = world.spawn();
            world
                .insert(
                    light,
                    // Down and away from the eye, so it lands on the face the
                    // camera sees rather than grazing it.
                    Light::sun(sim::Vec3::new(0.2, -0.4, -1.0), 0x00ff_ffff, 3.0),
                )
                .unwrap();
        }
        let mut extracted = Extracted::default();
        extracted
            .transforms::<Renderable>(&world, sim::DVec3::ZERO, Frustum::UNBOUNDED)
            .unwrap();
        extracted.append_lights(&world).unwrap();
        extracted
    }

    #[test]
    fn the_v1_pass_list_puts_a_declared_box_on_the_target() {
        const EXTENT: (u32, u32) = (64, 64);
        let extracted = one_lit_box(true);

        // Through the public offscreen entry point, not around it: this is the
        // path gg-golden gates on, and a test that assembled the same passes
        // beside it would prove them about itself.
        let mut renderer = OffscreenRenderer::new(EXTENT).unwrap();
        let frame = renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();

        // Every pass the graph derived is a pass the RHI was handed, in the
        // order the dump prints — §6 M6's "matches the executed order", as a
        // machine rather than as a claim about a text file. `order` is read off
        // the executed list, so this is the submission itself.
        // One shadow pass per cascade (§6 M15.3), nearest first, then the rest.
        assert_eq!(
            frame.order,
            [
                "shadow.0",
                "shadow.1",
                "shadow.2",
                "shadow.3",
                "depth-prepass",
                "forward-opaque",
                "post",
                "readback",
                "frame-end"
            ]
        );
        for name in &frame.order {
            assert!(
                frame.dump.contains(name.as_str()),
                "the dump names every executed pass: {name}"
            );
        }

        let at = |x: u32, y: u32| {
            let i = ((y * EXTENT.0 + x) * 4) as usize;
            [frame.pixels[i], frame.pixels[i + 1], frame.pixels[i + 2]]
        };
        let middle = at(EXTENT.0 / 2, EXTENT.1 / 2);
        assert!(
            middle[0] > 0x40,
            "the box is there and it is red: {middle:?}"
        );
        // Not "and only red" any more, and that is the milestone rather than a
        // regression: a dielectric's specular highlight is white by
        // construction (§6 M11), so a lit red box has a little of both other
        // channels. What is still true is that red dominates.
        assert!(
            middle[0] > middle[1] * 3 && middle[0] > middle[2] * 3,
            "red still dominates: {middle:?}"
        );
        assert_eq!(at(0, 0), [0, 0, 0], "the corners are still the clear");

        assert!(
            renderer.shutdown().clean(),
            "no leaks, no validation messages"
        );
    }

    /// A frame nothing casts in declares no shadow pass — so the graph is the
    /// frame rather than a superset of every frame, and an unlit scene does not
    /// allocate a shadow map to clear and never read.
    #[test]
    fn a_frame_with_no_sun_declares_no_shadow_pass() {
        const EXTENT: (u32, u32) = (64, 64);
        let extracted = one_lit_box(false);
        let mut renderer = OffscreenRenderer::new(EXTENT).unwrap();
        let frame = renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();

        assert_eq!(
            frame.order,
            [
                "depth-prepass",
                "forward-opaque",
                "post",
                "readback",
                "frame-end"
            ]
        );

        // And the box is *dim*, not gone: the ambient term is what an unlit
        // surface gets, and pure black would be indistinguishable from a mesh
        // that failed to draw.
        let i = ((EXTENT.1 / 2 * EXTENT.0 + EXTENT.0 / 2) * 4) as usize;
        let middle = [frame.pixels[i], frame.pixels[i + 1], frame.pixels[i + 2]];
        assert!(
            middle[0] > 0 && middle[0] < 0x40,
            "ambient only: {middle:?}"
        );

        assert!(
            renderer.shutdown().clean(),
            "no leaks, no validation messages"
        );
    }

    /// A box two metres over a floor, a sun straight down, and the patch of
    /// floor beneath it darker than the floor beside it.
    ///
    /// The one claim §6 M11 makes that no amount of green pipeline plumbing
    /// implies: the shadow map is rendered from the light, sampled by the
    /// forward pass, and compared the right way round. Reverse-Z means an
    /// inverted comparison shadows exactly what is lit, which is a picture that
    /// still looks like *a* picture — so it is asserted rather than eyeballed.
    #[test]
    fn a_box_over_a_floor_casts_a_shadow_onto_it() {
        use gg_ecs::World;
        use gg_ecs::boundary::{Light, Renderable};
        use gg_math::sim;

        const EXTENT: (u32, u32) = (64, 64);
        let mut world = World::new();
        world.register::<Renderable>().unwrap();
        world.register::<Light>().unwrap();
        let mut spawn = |r: Renderable| {
            let e = world.spawn();
            world.insert(e, r).unwrap();
        };
        // A wide slab whose top face is at y = -1.9, and a box spanning
        // y in [-1, 1] centred ten metres out.
        spawn(Renderable::boxed(
            sim::DVec3::new(0.0, -2.0, -10.0),
            sim::Vec3::new(10.0, 0.1, 10.0),
            0x00ff_ffff,
        ));
        spawn(Renderable::boxed(
            sim::DVec3::new(0.0, 0.0, -10.0),
            sim::Vec3::splat(1.0),
            0x00ff_ffff,
        ));
        let light = world.spawn();
        world
            .insert(
                light,
                // Straight down, so the shadow lands directly beneath the box
                // and the geometry below is arithmetic rather than guesswork.
                Light::sun(sim::Vec3::new(0.0, -1.0, 0.0), 0x00ff_ffff, 2.0),
            )
            .unwrap();

        let mut extracted = Extracted::default();
        extracted
            .transforms::<Renderable>(&world, sim::DVec3::ZERO, Frustum::UNBOUNDED)
            .unwrap();
        extracted.append_lights(&world).unwrap();

        let mut renderer = OffscreenRenderer::new(EXTENT).unwrap();
        let frame = renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();
        let at = |x: u32, y: u32| {
            let i = ((y * EXTENT.0 + x) * 4) as usize;
            u32::from(frame.pixels[i])
        };

        // Row 43 is below the box's silhouette and lands on floor about ten
        // metres out — inside the shadow at the centre column, outside it three
        // metres to the side.
        let shadowed = at(32, 43);
        let lit = at(52, 43);
        assert!(lit > 0x30, "the floor beside the box is lit: {lit}");
        assert!(
            shadowed * 2 < lit,
            "the floor under the box is shadowed: {shadowed} vs {lit}"
        );
        // And not *black*: one cascade with a 3x3 filter still leaves the
        // ambient term, which is what stops a shadow from being a hole.
        assert!(shadowed > 0, "a shadow is dark, not absent: {shadowed}");

        assert!(
            renderer.shutdown().clean(),
            "no leaks, no validation messages"
        );
    }

    /// The luminance histogram measures the frame it was rendered beside.
    ///
    /// Windowed only would have meant windowed only *tested* — and §1.5 means no
    /// automated tier opens a window, so the row would have shipped on a path
    /// nothing ever ran. It is available offscreen for exactly that reason.
    #[test]
    fn the_histogram_bins_the_frame_it_measured() {
        const EXTENT: (u32, u32) = (64, 64);
        // Registered once for the process; other tests in this binary share it.
        static ONCE: std::sync::Once = std::sync::Once::new();
        ONCE.call_once(|| cvars::register().expect("the render knobs are unclaimed"));

        let extracted = one_lit_box(true);
        let mut renderer = OffscreenRenderer::new(EXTENT).unwrap();

        // Off: no pass, no bins, and the graph does not name a grid.
        let frame = renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();
        assert!(renderer.luminance().is_none(), "off by default");
        assert!(!frame.order.iter().any(|name| name == "luminance"));

        cvars::HISTOGRAM.set_bool(true);
        let frame = renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();
        assert!(frame.order.iter().any(|name| name == "luminance"));
        let bins = renderer
            .luminance()
            .expect("a frame measured one")
            .to_owned();
        cvars::HISTOGRAM.reset();

        // Every sampled texel landed in a bucket — the grid is a fixed size, so
        // this is the count and not an estimate.
        let total: u32 = bins.iter().sum();
        assert_eq!(total, luminance::GRID.0 * luminance::GRID.1);
        // The frame is a lit red box on black, so the mass is at both ends: most
        // of the target is the clear, and the box is bright enough to sit above
        // it. A histogram that put everything in one bucket would be a histogram
        // of a constant.
        assert!(bins[0] > 0, "the clear is black: {:?}", &bins[..4]);
        let lit: u32 = bins[1..].iter().sum();
        assert!(lit > 0, "and the box is not: {bins:?}");

        // Turning it off again stops reporting, rather than freezing the last
        // frame's numbers on screen.
        renderer
            .frame(&extracted, &View::default(), [0.0, 0.0, 0.0, 1.0], &[])
            .unwrap();
        assert!(renderer.luminance().is_none(), "and off again");

        assert!(
            renderer.shutdown().clean(),
            "no leaks, no validation messages"
        );
    }

    #[test]
    fn colours_arrive_as_the_game_wrote_them() {
        assert_eq!(srgb_to_linear(0x0000_0000), [0.0, 0.0, 0.0, 1.0]);
        assert_eq!(srgb_to_linear(0x00ff_ffff), [1.0, 1.0, 1.0, 1.0]);
        // Channel order, which is the one thing a swap here would silently
        // survive: pure red stays in the first slot.
        let red = srgb_to_linear(0x00ff_0000);
        assert_eq!((red[0], red[1], red[2]), (1.0, 0.0, 0.0));
        // Mid-grey is where the curve is chosen: squaring 128/255 gives 0.2520,
        // the sRGB EOTF 0.2159. The endpoints agree under either, so only this
        // asserts which one is in use.
        let grey = srgb_to_linear(0x0080_8080);
        assert!((grey[0] - 0.215_860_5).abs() < 1e-6, "{grey:?}");
    }

    #[test]
    // The reference value is computed here and never ships, so §3's ban on
    // `powf` — a portability rule about what crosses the membrane — does not
    // reach it; the table it checks is what ships.
    #[allow(clippy::disallowed_methods)]
    fn the_transfer_function_is_srgb() {
        for (byte, &entry) in SRGB_EOTF.iter().enumerate() {
            let c = byte as f64 / 255.0;
            let reference = if c <= 0.040_45 {
                c / 12.92
            } else {
                ((c + 0.055) / 1.055).powf(2.4)
            } as f32;
            // One ulp at the top of the range: the table is the same formula,
            // and only a differing libm last bit is forgiven.
            assert!(
                (entry - reference).abs() <= f32::EPSILON,
                "byte {byte}: {entry} vs {reference}"
            );
        }
        assert_eq!(SRGB_EOTF[0], 0.0);
        assert_eq!(SRGB_EOTF[255], 1.0);
    }
}
