//! `gg-render` (§4.5) — passes and frame orchestration.
//!
//! **This is v0 and it is not the render graph.** §4.5's v1 target list opens
//! with "forward opaque pass"; [`Renderer`] is that pass, alone, born at M5 for a
//! reason that is structural rather than impatient: §2 gives the shell the
//! window and the renderer in *every* tier, and §3 caps the shell at zero engine
//! logic — so a cube mesh, a pipeline and a per-instance push constant have
//! nowhere else in the tree to live. M6 replaces the inside of this crate with
//! virtual resources and derived barriers. The three calls the shell makes
//! ([`Renderer::new`], [`Renderer::frame`], [`Renderer::shutdown`]) are the
//! part meant to survive that.
//!
//! It draws exactly one primitive — a box — because the game says where, how big
//! and what colour, and nothing else (`gg_ecs::boundary::Renderable`). A
//! renderer with more opinions than that would be a renderer the Ugly Game
//! cannot restyle without rebuilding the engine, which is the wrong half of the
//! cooperative loop to make expensive.

#![warn(missing_docs)]

/// Generated by `cargo xtask shaders` from `shaders/ugly.slang` (§4.4).
pub mod shaders_gen {
    /// The v0 pass: push-constant struct + embedded SPIR-V.
    pub mod ugly;
}

use gg_extract::{Extracted, Instance};
use gg_math::render;
use gg_rhi::{
    BufferDesc, BufferHandle, BufferKind, DeviceAddress, DeviceReport, DrawSpec, FrameOutcome,
    PipelineDesc, PipelineHandle, Rhi, RhiError, ShutdownReport,
};
use raw_window_handle::{HasDisplayHandle, HasWindowHandle};
use shaders_gen::ugly as shader;

/// One vertex, mirroring `ugly.slang`'s `VERTEX_STRIDE` byte layout. The shader
/// reads these at hardcoded offsets through a device address, so the layout is
/// frozen below rather than trusted.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
struct Vertex {
    position: [f32; 3],
    normal: [f32; 3],
}

const _: () = {
    assert!(core::mem::size_of::<Vertex>() == 24);
    assert!(core::mem::offset_of!(Vertex, normal) == 12);
};

/// Where the frame is seen from, on the render side of the membrane.
///
/// Position is absent on purpose: it never crosses. [`Extracted`] arrives
/// already camera-relative, so the eye *is* the origin here and the view matrix
/// carries rotation only — which is what makes a camera 10^12 m out render
/// without jitter (§1.4, §4.2.1).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct View {
    /// Rotation about +Y, radians.
    pub yaw: f32,
    /// Rotation about the camera's right axis, radians.
    pub pitch: f32,
    /// Vertical field of view, radians.
    pub fov_y: f32,
    /// Near plane. With reverse-Z and an infinite far plane this is the *only*
    /// depth-precision knob there is (§2, Math row).
    pub near: f32,
}

impl Default for View {
    fn default() -> Self {
        View {
            yaw: 0.0,
            pitch: 0.0,
            fov_y: 1.0,
            near: 0.05,
        }
    }
}

impl View {
    fn rotation(&self) -> render::Quat {
        // YXZ: yaw about world +Y first, then pitch about the rotated right
        // axis — the fly-camera order, and the one that never rolls.
        render::Quat::from_euler(render::EulerRot::YXZ, self.yaw, self.pitch, 0.0)
    }

    /// Camera-relative world → clip.
    fn view_projection(&self, extent: (u32, u32)) -> render::Mat4 {
        let rotation = self.rotation();
        let aspect = extent.0.max(1) as f32 / extent.1.max(1) as f32;
        let view = render::camera::rh::view::look_to_mat4(
            render::Vec3::ZERO,
            rotation * render::Vec3::NEG_Z,
            rotation * render::Vec3::Y,
        );
        render::perspective_reverse_z(self.fov_y, aspect, self.near) * view
    }
}

/// A window's GPU state and the passes over it — what the shell holds.
///
/// It owns the [`Rhi`] rather than taking one per call so the shell never names
/// `gg-rhi` at all: §3 caps the shell at zero engine logic, and a host that
/// creates pipelines is past that line whatever the line count says.
pub struct Renderer {
    rhi: Rhi,
    pass: BoxPass,
}

impl Renderer {
    /// Bring up the device and swapchain for `window`, and upload the pass.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses: no device, no surface, or a failed upload.
    ///
    /// # Safety of teardown
    ///
    /// The surface may not outlive the window it came from, so [`Renderer::shutdown`]
    /// must run while the window is still alive (§4.3).
    pub fn new(
        window: &(impl HasWindowHandle + HasDisplayHandle),
        extent: (u32, u32),
    ) -> Result<Self, RhiError> {
        let mut rhi = Rhi::new(window, extent)?;
        let pass = BoxPass::new(&mut rhi)?;
        Ok(Renderer { rhi, pass })
    }

    /// Which device was chosen, and what it can do (§4.3).
    pub fn device(&self) -> &DeviceReport {
        self.rhi.device_report()
    }

    /// New window size in physical pixels. `(0, 0)` suspends rather than
    /// recreates.
    pub fn resize(&mut self, width: u32, height: u32) {
        self.rhi.resize(width, height);
    }

    /// One frame: clear, draw every instance, present.
    ///
    /// # Errors
    ///
    /// Whatever the RHI refuses while recording, submitting or presenting.
    pub fn frame(
        &mut self,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
    ) -> Result<FrameOutcome, RhiError> {
        self.pass.draw(&mut self.rhi, extracted, view, color)
    }

    /// Release everything and account for it (§4.3, §5.4).
    pub fn shutdown(mut self) -> ShutdownReport {
        // A refusal here can only be a handle this struct did not issue, which
        // cannot happen — and if it somehow did, the unreleased memory shows up
        // in the report below, which is the check that actually matters.
        drop(self.pass.destroy(&mut self.rhi));
        self.rhi.shutdown()
    }
}

/// The v0 forward pass: one pipeline, one unit box, one draw per instance.
struct BoxPass {
    pipeline: PipelineHandle,
    vertices: BufferHandle,
    indices: BufferHandle,
    vertex_address: DeviceAddress,
    index_count: u32,
    /// Reused across frames. The push constants have to outlive the [`DrawSpec`]s
    /// that borrow them, and extract already refuses to allocate per frame — a
    /// buffer beside it that did would undo that.
    pushes: Vec<shader::UglyPush>,
}

impl BoxPass {
    /// Upload the box and build the pipeline. One flush, at startup.
    fn new(rhi: &mut Rhi) -> Result<Self, RhiError> {
        let (vertices, indices) = unit_box();
        let vertex_bytes = bytemuck::cast_slice(&vertices);
        let index_bytes = bytemuck::cast_slice(&indices);

        let vertex_buffer = rhi.create_buffer(&BufferDesc {
            name: "render.box.vertices",
            size: vertex_bytes.len() as u64,
            kind: BufferKind::Storage,
        })?;
        let index_buffer = rhi.create_buffer(&BufferDesc {
            name: "render.box.indices",
            size: index_bytes.len() as u64,
            kind: BufferKind::Index,
        })?;
        rhi.upload_buffer(vertex_buffer, 0, vertex_bytes)?;
        rhi.upload_buffer(index_buffer, 0, index_bytes)?;
        rhi.flush_uploads()?;

        Ok(BoxPass {
            pipeline: rhi.create_pipeline(&pipeline_desc())?,
            vertices: vertex_buffer,
            indices: index_buffer,
            vertex_address: rhi.buffer_address(vertex_buffer)?,
            index_count: indices.len() as u32,
            pushes: Vec::new(),
        })
    }

    /// Clear to `color`, then draw every instance. One pass, one present.
    fn draw(
        &mut self,
        rhi: &mut Rhi,
        extracted: &Extracted,
        view: &View,
        color: [f32; 4],
    ) -> Result<FrameOutcome, RhiError> {
        let view_projection = view.view_projection(rhi.swapchain_extent());
        let address = self.vertex_address;
        self.pushes.clear();
        self.pushes.extend(
            extracted
                .instances
                .iter()
                .map(|instance| push_for(address, view_projection, instance)),
        );
        // A draw call per box, which is the honest cost until M6 batches: the
        // Ugly Game draws a few hundred, and instancing here would be a second
        // implementation for the graph to replace.
        let draws: Vec<DrawSpec<'_>> = self
            .pushes
            .iter()
            .map(|push| DrawSpec {
                pipeline: self.pipeline,
                push_constants: bytemuck::bytes_of(push),
                count: self.index_count,
                index_buffer: Some(self.indices),
            })
            .collect();
        rhi.render_frame(color, &draws)
    }

    /// Release the pipeline and both buffers.
    fn destroy(self, rhi: &mut Rhi) -> Result<(), RhiError> {
        rhi.destroy_pipeline(self.pipeline)?;
        rhi.destroy_buffer(self.vertices)?;
        rhi.destroy_buffer(self.indices)
    }
}

/// The v0 pass, straight from the embedded offline build.
///
/// Depth on: reverse-Z is what sorts one box behind another, and a box drawn
/// without it would be a box drawn in whatever order extract happened to visit.
fn pipeline_desc() -> PipelineDesc<'static> {
    PipelineDesc {
        name: "ugly",
        vs_spirv: shader::VS_MAIN_SPIRV,
        vs_entry: shader::VS_MAIN_ENTRY,
        fs_spirv: shader::FS_MAIN_SPIRV,
        fs_entry: shader::FS_MAIN_ENTRY,
        push_constant_size: core::mem::size_of::<shader::UglyPush>() as u32,
        depth: true,
    }
}

/// Push constants for one instance.
fn push_for(
    vertices: DeviceAddress,
    view_projection: render::Mat4,
    instance: &Instance,
) -> shader::UglyPush {
    let model = render::Mat4::from_scale_rotation_translation(
        instance.half_extent,
        instance.rotation,
        instance.offset,
    );
    shader::UglyPush::new(
        render::rows(view_projection * model),
        vertices,
        srgb_to_linear(instance.color),
        instance.rotation.to_array(),
    )
}

/// `0x00RRGGBB` → linear rgb, with alpha unused.
///
/// The swapchain target encodes sRGB, so a colour handed over as sRGB bytes has
/// to be linearized here or every tint comes out washed. Gamma 2.0 — squaring —
/// rather than 2.2 or the piecewise curve: `powf` is banned engine-wide (§3, and
/// it would want `gg_math::sim` in a crate downstream of the membrane), this is
/// a tint on an untextured box, and the exact transfer function is `ggc`'s
/// problem at import (§4.6).
fn srgb_to_linear(color: u32) -> [f32; 4] {
    let channel = |shift: u32| {
        let byte = ((color >> shift) & 0xff) as f32 / 255.0;
        byte * byte
    };
    [channel(16), channel(8), channel(0), 1.0]
}

/// A box of half-extent 1 — the instance's scale is what gives it a size. 24
/// vertices so every face carries its own normal, 36 indices.
fn unit_box() -> (Vec<Vertex>, Vec<u32>) {
    // (normal, u axis, v axis) per face, u x v pointing outward.
    const FACES: [([f32; 3], [f32; 3], [f32; 3]); 6] = [
        ([1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]),
        ([-1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0]),
        ([0.0, 1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, -1.0]),
        ([0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]),
        ([0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
        ([0.0, 0.0, -1.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]),
    ];
    const CORNERS: [(f32, f32); 4] = [(-1.0, -1.0), (1.0, -1.0), (1.0, 1.0), (-1.0, 1.0)];

    let mut vertices = Vec::with_capacity(24);
    let mut indices = Vec::with_capacity(36);
    for (normal, u_axis, v_axis) in FACES {
        let base = vertices.len() as u32;
        for (u, v) in CORNERS {
            vertices.push(Vertex {
                position: [
                    normal[0] + u * u_axis[0] + v * v_axis[0],
                    normal[1] + u * u_axis[1] + v * v_axis[1],
                    normal[2] + u * u_axis[2] + v * v_axis[2],
                ],
                normal,
            });
        }
        indices.extend_from_slice(&[base, base + 1, base + 2, base, base + 2, base + 3]);
    }
    (vertices, indices)
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;

    #[test]
    fn the_box_is_closed_and_its_normals_point_outward() {
        let (vertices, indices) = unit_box();
        assert_eq!(vertices.len(), 24);
        assert_eq!(indices.len(), 36);
        for v in &vertices {
            for axis in v.position {
                assert!(
                    (axis.abs() - 1.0).abs() < 1e-6,
                    "corner at {:?}",
                    v.position
                );
            }
            let dot = v.position[0] * v.normal[0]
                + v.position[1] * v.normal[1]
                + v.position[2] * v.normal[2];
            assert!(dot > 0.0, "normal {:?} faces inward", v.normal);
        }
    }

    #[test]
    fn the_near_plane_maps_to_one_and_the_far_distance_to_zero() {
        // Reverse-Z, the §2-locked convention, checked where a projection is
        // actually built rather than only where it is defined: a matrix assembled
        // the ordinary way renders a scene that is subtly, consistently wrong.
        let view = View::default();
        let clip = view.view_projection((640, 360));
        let near = clip * render::Vec4::new(0.0, 0.0, -view.near, 1.0);
        let far = clip * render::Vec4::new(0.0, 0.0, -1.0e9, 1.0);
        assert!((near.z / near.w - 1.0).abs() < 1e-5, "near maps to 1");
        assert!((far.z / far.w).abs() < 1e-5, "the far distance maps to 0");
    }

    #[test]
    fn a_yawed_view_looks_where_the_yaw_says() {
        let view = View {
            yaw: core::f32::consts::FRAC_PI_2,
            ..View::default()
        };
        // +90° of yaw about +Y turns the -Z forward axis onto -X.
        let forward = view.rotation() * render::Vec3::NEG_Z;
        assert!(
            (forward - render::Vec3::NEG_X).length() < 1e-6,
            "{forward:?}"
        );
    }

    /// The whole path with no window in it: a game component, extract's
    /// narrowing, the push constants, the shader, and pixels back (§1.5 — the
    /// only rendering an automated tier is allowed to do).
    #[test]
    fn a_box_the_game_declared_lands_on_the_target() {
        use gg_ecs::World;
        use gg_ecs::boundary::Renderable;
        use gg_math::sim;
        use gg_rhi::{BufferDesc, BufferKind, DrawSpec, OffscreenRhi};

        const EXTENT: (u32, u32) = (64, 64);
        let mut world = World::new();
        world.register::<Renderable>().unwrap();
        let entity = world.spawn();
        world
            .insert(
                entity,
                // Dead ahead of an unrotated eye, big enough to cover the middle
                // and small enough to leave the corners clear.
                Renderable::boxed(
                    sim::DVec3::new(0.0, 0.0, -4.0),
                    sim::Vec3::splat(1.0),
                    0x00ff_0000,
                ),
            )
            .unwrap();
        let mut extracted = Extracted::default();
        extracted
            .transforms::<Renderable>(&world, sim::DVec3::ZERO)
            .unwrap();

        let mut rhi = OffscreenRhi::new(EXTENT).unwrap();
        let (vertices, indices) = unit_box();
        let vertex_bytes: &[u8] = bytemuck::cast_slice(&vertices);
        let index_bytes: &[u8] = bytemuck::cast_slice(&indices);
        let vertex_buffer = rhi
            .create_buffer(&BufferDesc {
                name: "test.box.vertices",
                size: vertex_bytes.len() as u64,
                kind: BufferKind::Storage,
            })
            .unwrap();
        let index_buffer = rhi
            .create_buffer(&BufferDesc {
                name: "test.box.indices",
                size: index_bytes.len() as u64,
                kind: BufferKind::Index,
            })
            .unwrap();
        rhi.upload_buffer(vertex_buffer, 0, vertex_bytes).unwrap();
        rhi.upload_buffer(index_buffer, 0, index_bytes).unwrap();
        rhi.flush_uploads().unwrap();
        let pipeline = rhi.create_pipeline(&pipeline_desc()).unwrap();
        let address = rhi.buffer_address(vertex_buffer).unwrap();

        let view = View::default();
        let push = push_for(
            address,
            view.view_projection(EXTENT),
            &extracted.instances[0],
        );
        let pixels = rhi
            .render(
                [0.0, 0.0, 0.0, 1.0],
                &[DrawSpec {
                    pipeline,
                    push_constants: bytemuck::bytes_of(&push),
                    count: indices.len() as u32,
                    index_buffer: Some(index_buffer),
                }],
            )
            .unwrap();

        let at = |x: u32, y: u32| {
            let i = ((y * EXTENT.0 + x) * 4) as usize;
            [pixels[i], pixels[i + 1], pixels[i + 2]]
        };
        let middle = at(EXTENT.0 / 2, EXTENT.1 / 2);
        assert!(
            middle[0] > 0x40,
            "the box is there and it is red: {middle:?}"
        );
        assert_eq!((middle[1], middle[2]), (0, 0), "and only red");
        assert_eq!(at(0, 0), [0, 0, 0], "the corners are still the clear");

        drop(rhi.destroy_pipeline(pipeline));
        drop(rhi.destroy_buffer(vertex_buffer));
        drop(rhi.destroy_buffer(index_buffer));
        assert!(rhi.shutdown().clean(), "no leaks, no validation messages");
    }

    #[test]
    fn colours_arrive_as_the_game_wrote_them() {
        assert_eq!(srgb_to_linear(0x0000_0000), [0.0, 0.0, 0.0, 1.0]);
        assert_eq!(srgb_to_linear(0x00ff_ffff), [1.0, 1.0, 1.0, 1.0]);
        // Channel order, which is the one thing a swap here would silently
        // survive: pure red stays in the first slot.
        let red = srgb_to_linear(0x00ff_0000);
        assert_eq!((red[0], red[1], red[2]), (1.0, 0.0, 0.0));
    }
}
