// @generated by `cargo xtask shaders` from shaders/triangle.slang — do not edit.
// source-hash: sha256:6b8cc9f4deb3ee5509328d3209f73f4998c1cf032ddbc07d9f15748f13f176c6 generator: v4
//
// Layout facts reflected from Slang, frozen as compile-time assertions:
// a shader/CPU struct mismatch is a build error (PLAN.md §4.4).

/// Push-constant block `TrianglePush` — std430 layout, 80 bytes.
#[repr(C)]
#[derive(Clone, Copy, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct TrianglePush {
    /// offset 0
    pub transform: [[f32; 4]; 4],
    /// offset 64
    pub tint: [f32; 4],
}

impl TrianglePush {
    /// Construct with every padding byte zeroed.
    pub fn new(transform: [[f32; 4]; 4], tint: [f32; 4]) -> Self {
        Self { transform, tint }
    }
}

const _: () = {
    assert!(core::mem::size_of::<TrianglePush>() == 80);
    assert!(core::mem::offset_of!(TrianglePush, transform) == 0);
    assert!(core::mem::offset_of!(TrianglePush, tint) == 64);
};

/// SPIR-V for entry point `vs_main` (vertex).
pub static VS_MAIN_SPIRV: &[u8] = include_bytes!("triangle.vs_main.spv");
/// The `OpEntryPoint` name inside [`VS_MAIN_SPIRV`].
pub const VS_MAIN_ENTRY: &str = "main";

/// SPIR-V for entry point `fs_main` (fragment).
pub static FS_MAIN_SPIRV: &[u8] = include_bytes!("triangle.fs_main.spv");
/// The `OpEntryPoint` name inside [`FS_MAIN_SPIRV`].
pub const FS_MAIN_ENTRY: &str = "main";
