//! `cargo xtask public-api` — the §5.10 surface gate.
//!
//! `gg-ecs`'s API is designed before its real access patterns exist (§2), so
//! "small and stable" has to be held by a machine rather than by intent: the
//! checked-in baseline is the promise, and widening it is a diff someone has to
//! approve rather than a convenience an agent adds at M10 to unblock itself.
//!
//! `cargo-public-api` needs rustdoc's unstable JSON output, so this is the one
//! gate that runs on a **pinned nightly** rather than the pinned stable of §2.
//! That is not a second toolchain for the engine — nothing built here ships or
//! is linked; the nightly only renders a text file. It is pinned anyway,
//! because rustdoc's JSON rendering shifts between nightlies and an unpinned
//! one would make the baseline drift on its own.

use crate::util::{run_capture, workspace_root};
use std::path::PathBuf;
use std::process::Command;

/// The pinned nightly. Bumping it re-renders every baseline; do it deliberately
/// and read the resulting diff, which is exactly the point of the gate.
pub(crate) const NIGHTLY: &str = "nightly-2026-07-20";

/// Crates whose public surface is held (§3 complexity budgets). `gg-ecs-derive`
/// is absent on purpose: a proc-macro crate's surface is three derive names,
/// and its real contract is the compile-fail suite in `tests/reject/`.
///
/// `gg-abi` joined at M5, and for a reason the other entry does not have: its
/// surface *is* the compatibility story (§4.2.2), so an item appearing or
/// disappearing there is an ABI event by definition. It also closes a hole this
/// gate opened itself — moving `Entity` and `ColumnView` down out of `gg-ecs`
/// took 78 inherent items off that baseline, and until now they landed under no
/// baseline at all.
/// `gg-rhi` and `gg-render` joined at M12, which is what §5.10 means by "extended
/// at v0.1". Their case is the one no machine can make: §4.3 asks that `gg-rhi`
/// be *shaped like our engine* rather than like a backend, and a baseline is the
/// only way that review happens on every change instead of once. Reading the
/// first render is part of the price — it retired five accidental exports
/// (two functions returning a private type, a generated-code module, the upload
/// scheduler, and a validation counter) before freezing what remained.
const GATED: &[&str] = &["gg-abi", "gg-ecs", "gg-render", "gg-rhi"];

/// `-sss`: omit blanket, auto-trait and auto-derived impls. Those are noise
/// generated by the derives and by the compiler, and a baseline nobody can read
/// is a baseline nobody reviews.
const SIMPLIFY: &str = "-sss";

fn baseline_path(krate: &str) -> PathBuf {
    workspace_root()
        .join("crates")
        .join(krate)
        .join("public-api.txt")
}

fn render(krate: &str) -> anyhow::Result<String> {
    let mut cmd = Command::new("cargo");
    cmd.current_dir(workspace_root())
        .env("GG_HEADLESS", "1")
        .args([&format!("+{NIGHTLY}"), "public-api", "-p", krate, SIMPLIFY]);
    run_capture(&mut cmd, &format!("cargo public-api -p {krate}")).map_err(|e| {
        anyhow::anyhow!(
            "{e}\n\nThis gate needs the pinned nightly and cargo-public-api:\n  \
             rustup toolchain install {NIGHTLY}\n  cargo install cargo-public-api"
        )
    })
}

/// Compare each gated crate's rendered surface against its baseline.
pub fn check() -> anyhow::Result<()> {
    for krate in GATED {
        let path = baseline_path(krate);
        let expected = std::fs::read_to_string(&path)
            .map_err(|e| anyhow::anyhow!("no public-api baseline at {}: {e}", path.display()))?;
        let actual = render(krate)?;
        if normalize(&expected) == normalize(&actual) {
            println!(
                "xtask public-api: {krate} matches its baseline ({} items)",
                normalize(&actual).len()
            );
            continue;
        }
        anyhow::bail!(
            "public surface of `{krate}` changed (§5.10)\n{}\n\nIf the change is intended, \
             `cargo xtask public-api --bless` rewrites the baseline — and the diff belongs in \
             the review, not in a fixup.",
            diff(&normalize(&expected), &normalize(&actual))
        );
    }
    Ok(())
}

/// Rewrite the baselines. Deliberate, like a golden `bless`.
pub fn bless() -> anyhow::Result<()> {
    for krate in GATED {
        let rendered = render(krate)?;
        let path = baseline_path(krate);
        std::fs::write(&path, &rendered)?;
        println!("xtask public-api: blessed {}", path.display());
    }
    Ok(())
}

pub fn run(args: &[&str]) -> anyhow::Result<()> {
    if args.contains(&"--bless") {
        bless()
    } else {
        check()
    }
}

/// Line-wise, trailing whitespace and blank lines dropped — so a stray newline
/// at the end of a file is not a public-API event.
fn normalize(text: &str) -> Vec<&str> {
    text.lines()
        .map(str::trim_end)
        .filter(|l| !l.is_empty())
        .collect()
}

/// A plain added/removed summary. Both sides are sorted by construction, so set
/// difference is the whole story and no LCS is needed.
fn diff(expected: &[&str], actual: &[&str]) -> String {
    use std::collections::BTreeSet;
    let before: BTreeSet<&str> = expected.iter().copied().collect();
    let after: BTreeSet<&str> = actual.iter().copied().collect();
    let mut out = String::new();
    for line in after.difference(&before) {
        out.push_str("  + ");
        out.push_str(line);
        out.push('\n');
    }
    for line in before.difference(&after) {
        out.push_str("  - ");
        out.push_str(line);
        out.push('\n');
    }
    if out.is_empty() {
        out.push_str("  (item order changed but the set did not)\n");
    }
    out
}
